---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind. 
---
= Aktuelle Änderungen in der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind.  Eine vollständige Versionshistorie finden Sie unterlink:release-notes-index.html["Vollständiger Satz der Versionshinweise"] für jeden einzelnen Dienst.

[NOTE]
====
Die folgenden Dienste wurden eingestellt:

Edge-Caching:: Der Edge-Caching-Dienst wurde am 7. August 2024 entfernt.
Kubernetes:: Die Unterstützung für die Erkennung und Verwaltung von Kubernetes-Clustern wurde am 7. August 2024 entfernt.
Migrationsberichte:: Der Dienst für Migrationsberichte wurde am 7. August 2024 entfernt.
Betriebsstabilität:: Die Funktionen zur betrieblichen Ausfallsicherheit wurden am 22. August 2025 entfernt.
Sanierung:: Der Sanierungsdienst wurde am 22. April 2024 entfernt.


====


== 15. Juni 2026



=== Konsoleneinrichtung und -verwaltung



==== Veröffentlichung im privaten Modus (4.7.0)

Eine neue Version des privaten Modus steht jetzt zum Download aus dem https://mysupport.netapp.com/site/downloads["NetApp Support Site"^] bereit.

Die Version 4.7.0 enthält Aktualisierungen der folgenden NetApp Console-Komponenten und -Dienste.

[cols="3*"]
|===
| Komponente oder Service | In dieser Version enthalten | Änderungen seit der vorherigen privaten Modus-Version 


| Konsolenagent | 4.7.0 | Gehen Sie zu  https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2026-05-11.html["Was ist neu auf der NetApp Console-Seite"^] und informieren Sie sich über die Änderungen in Version 4.7.0. 


| NetApp Backup and Recovery | 5.4.0 (08. Juni 2026) | Gehe zu https://docs.netapp.com/us-en/data-services-backup-recovery/whats-new.html["Was ist neu auf der Seite NetApp Backup and Recovery"^]. 


| NetApp Data Classification | 1.54.0 (11. Mai 2026) | Gehe zu https://docs.netapp.com/us-en/data-services-data-classification/whats-new.html["Was ist neu auf der Seite NetApp Klassifizierung"^]. 
|===


=== Sicherung und Wiederherstellung



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.06*: Diese Version enthält Trident Protect 26.06.
* *Anwendungserstellung bei Wiederherstellung überspringen*: Die automatische Erstellung benutzerdefinierter Anwendungsressourcenobjekte kann während Wiederherstellungsvorgängen nun übersprungen werden. Dies reduziert unnötige Einträge im Anwendungsinventar.
* *Wiederherstellung persistenter Volume Claims in VMs*: Bei der Wiederherstellung von VM-basierten Anwendungen ist es jetzt möglich, einzelne persistente Volume Claims wiederherzustellen, ohne die gesamte virtuelle Maschine wiederherstellen zu müssen, was die Wiederherstellung beschleunigt, wenn bestimmte Festplatten oder Volumes von Beschädigungen oder Datenverlust betroffen sind.
* *Verbesserungen im Jobmonitor*: Die Überwachung von Jobs bietet jetzt eine verbesserte Transparenz bei Kubernetes-Schutzjobs. Detaillierte Statusinformationen zu Jobs und Subjobs sowie der jeweils verwendete Zielspeicher sind einsehbar.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



== 11. Juni 2026



=== Cloud Volumes ONTAP



==== Unterstützung für eine neue Azure-Region in Cloud Volumes ONTAP

Cloud Volumes ONTAP 9.12.1 GA und höher kann jetzt in Azure in der Region Malaysia West (malaysiawest) in einzelnen und mehreren Verfügbarkeitszonen bereitgestellt werden. Dies umfasst die Unterstützung sowohl für Einzelknoten- als auch für Hochverfügbarkeitsbereitstellungen (HA).

Eine Liste aller Regionen finden Sie unter https://bluexp.netapp.com/cloud-volumes-global-regions["Globale Regionskarte unter Azure"^].



== 08. Juni 2026



=== Sicherung und Wiederherstellung



==== ONTAP Volumes Workloads-Verbesserungen

In dieser Version führt ONTAP Volumes-Workloads die folgende Verbesserung ein:

*Unterstützung für S3-kompatiblen Cloud-Speicher*: NetApp Backup and Recovery für Volumes-Workloads unterstützt jetzt das Sichern in S3-kompatiblen Cloud-Speicher.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



==== Hyper-V-Workload-Verbesserungen

In dieser Version werden für Hyper-V-Workloads die folgenden Verbesserungen eingeführt:

* *Wiederherstellen von Dateien und Ordnern in einer Gast-VM – Verbesserungen*: Sie können jetzt Dateien und Ordner aus einem Snapshot auf primärem oder sekundärem Speicher in einer Gast-Windows-VM wiederherstellen. Diese Funktion wird nun für CIFS- und SAN-VMs unterstützt.
* *Schutzgruppen verwenden jetzt die Zeitzone des Hyper-V-Hosts*: Schutzgruppen verwenden nun die Zeitzone des Hyper-V-Hosts. Schutzgruppen, die vor der Einführung der Host-Zeitzonenplanung erstellt wurden, verwenden weiterhin ihre zuvor konfigurierte Zeit (typischerweise UTC). Damit diese Schutzgruppen die Zeitzone des Hyper-V-Hosts verwenden, ist es erforderlich, die Zeitpläne neu zu erstellen. Weitere Informationen sind unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für Hyper-V Workloads"] verfügbar.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Übersicht zum Schutz von Hyper-V-Workloads"].



==== VMware-Workload-Verbesserungen

In dieser Version führt VMware Workloads die folgende Verbesserung ein:

* *Schutzgruppen verwenden jetzt die Zeitzonenplanung des Hosts*: Schutzgruppen verwenden nun die Zeitzone des VMware vCenter Servers. Schutzgruppen, die vor der Einführung der Host-Zeitzonenplanung erstellt wurden, laufen weiterhin in ihrer zuvor konfigurierten Zeitzone (typischerweise UTC). Um die vCenter-Zeitzone zu nutzen, ist es erforderlich, die Zeitpläne neu zu erstellen. Weitere Informationen sind unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für VMware Workloads"] verfügbar.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



=== Datenklassifizierung



==== Allgemeine Verbesserungen

Diese Version der Datenklassifizierung beinhaltet Sicherheitsverbesserungen und Leistungsverbesserungen.



=== Notfallwiederherstellung



==== Kubernetes-Updates

Die Notfallwiederherstellung hat die folgenden Änderungen für Kubernetes-basierte Workloads eingeführt:



===== Testen Sie die Failover-Unterstützung für Kubernetes-Workloads

Die Notfallwiederherstellung unterstützt jetzt das Testen des Failover-Prozesses für Kubernetes-Workloads. Durch das Testen des Failovers können Sie Notfallwiederherstellungspläne validieren. Nach Abschluss des Tests können Sie den Test-Failover bereinigen, sodass das System die Testressourcen automatisch freigibt, um den Overhead zu reduzieren und die Konsistenz Ihrer Umgebung sicherzustellen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html#test-the-failover-process["Testen Sie den Failover-Prozess"^].



===== Geplante Test-Failover

Sie können jetzt Notfallwiederherstellungstests automatisieren, indem Sie Test-Failover planen. Sie können Zeitpläne für wiederkehrende Test-Failover festlegen, um Wiederherstellungspläne kontinuierlich ohne manuelle Eingriffe zu validieren, was dazu beiträgt, das Vertrauen in die Wiederherstellungsziele zu erhalten und Compliance-Anforderungen zu erfüllen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html#manage-replication-plans["Replikationspläne verwalten"^].



===== Geplante Erkennung von Kubernetes-Workloads

Mit der geplanten Erkennung können Sie steuern, wie häufig Disaster Recovery nach neuen Kubernetes-Workloads sucht. Sie können die Erkennungsintervalle an Ihren Betriebsrhythmus anpassen und so unnötigen Systemaufwand reduzieren, während gleichzeitig sichergestellt wird, dass neue Workloads rechtzeitig erkannt und geschützt werden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#edit-the-site-and-customize-the-discovery-schedule["Entdeckungszeitplan anpassen"^].



==== VMware-Updates



===== Schutz für leere Datenspeicher

Die Notfallwiederherstellung ermöglicht nun die Konfiguration des Schutzes für Datenspeicher, die keine virtuellen Maschinen (VMs) enthalten. Alle VMs, die dem Datenspeicher später hinzugefügt werden, werden von der Notfallwiederherstellung automatisch erkannt, zu diesem Zeitpunkt müssen Sie link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#add-subnet-mapping-for-a-vcenter-site["Mapping-Informationen"^] angeben.

Wenn Sie einen leeren Datenspeicher zu einem Schutzplan hinzufügen, müssen Sie entweder den Datenspeicher vor dem Failover aus dem Schutzplan entfernen oder ein erzwungenes Failover durchführen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Failover zu einem Remote-Standort"^].



===== Zuvor ausgeschlossene Datenspeicher in einen Schutzplan zurückholen

Datenspeicher, die zuvor vom Schutz ausgeschlossen waren, können nun wieder einbezogen werden. Diese Verbesserung bietet mehr Flexibilität bei der Verwaltung und Aktualisierung Ihrer Notfallwiederherstellungskonfigurationen im Laufe der Zeit.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Standorte, Ressourcengruppen und Replikationspläne verwalten"^].



===== Schnelleres Failover für VMFS-basierte Datastores

Die Notfallwiederherstellung hat die Failover-Performance für VMFS-basierte Datenspeicher verbessert. Host Bus Adapter (HBA) Rescan- und Datenspeicher-Mount-Operationen werden nun parallel ausgeführt, wodurch die gesamten Failover-Zeiten verkürzt und Ausfallzeiten während Wiederherstellungsereignissen minimiert werden.

Weitere Informationen zu Failover-Prozessen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Ausfallsicherung mit Notfallwiederherstellung"^].



=== Ransomware-Resilienz



==== Verbesserte Flexibilität für Schutzstrategien

Die Ransomware-Resilienz bietet jetzt mehr Flexibilität bei der Auswahl von Ransomware-Erkennungsstrategien. Bisher mussten alle Ransomware-Schutzstrategien die Erkennung von Verschlüsselung umfassen. Jetzt können Sie eine Ransomware-Schutzstrategie aktivieren, die ausschließlich die Erkennung des Nutzerverhaltens verwendet.

Schutzstrategien können weiterhin sowohl die Erkennung von Verschlüsselung _als auch_ die Erkennung verdächtigen Nutzerverhaltens umfassen. Auch das Blockieren von Dateierweiterungen kann in jede Schutzstrategie integriert werden.

Wenn Sie einen Teil der Schutzstrategie einer bestehenden Richtlinie deaktivieren, können alle unter der vorherigen Version der Richtlinie erstellten Warnungen nur als "Behoben" und nicht als "Abgelehnt" markiert werden. Wenn Sie beispielsweise eine Schutzstrategie hatten, die die Erkennung von Verschlüsselung und verdächtigem Benutzerverhalten umfasste, Sie aber die Verschlüsselungserkennung deaktiviert haben, können Sie nur eine bestehende Verschlüsselungswarnung für diese Arbeitslast als behoben markieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Schützen Sie Ihre Workloads mit NetApp Ransomware Resilience Schutzstrategien"^].



==== SOAR-Playbook-Erweiterungen

Die SOAR-Playbooks für Ransomware-Resilienz bieten nun Maßnahmen zur Behebung von Problemen, nachdem Sie einen Benutzer gesperrt oder ein Volume offline genommen haben. Sie können ein Volume nun wieder online schalten und einen Benutzer entsperren, wenn die Aktion nicht als Ransomware-Bedrohung eingestuft wurde.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integrieren Sie ein SOAR-Playbook"^].



=== Cloud Volumes ONTAP



==== Unterstützung für neue EC2-Instanzen für Cloud Volumes ONTAP in AWS

Cloud Volumes ONTAP 9.16.1 und höher unterstützen die EC2-Instanzfamilien M6id und M6idn sowohl für neue als auch bestehende Einzelknoten- und Hochverfügbarkeits-Bereitstellungen (HA) in AWS. Diese Instanzen der 6. Generation bieten im Vergleich zu den Allzwecksystemen der 5. Generation eine höhere Rechenleistung, verbesserte Netzwerkfunktionen und eine insgesamt höhere Performance.

* *M6id-Instanzen*: Sie bieten ein ausgewogenes Verhältnis von Rechenleistung und Arbeitsspeicher mit schnellem, mit niedriger Latenz lokalem NVMe-Speicher. Alle M6id-Instanzgrößen unterstützen Flash Cache. Diese Instanzen eignen sich hervorragend für Workloads wie Protokollierung und Medienverarbeitung.
* *M6idn-Instanzen*: Bieten dieselben lokalen NVMe-Speicherfunktionen wie M6id-Instanzen. Alle M6idn-Instanzgrößen unterstützen Flash Cache.


Wir empfehlen die kleineren Instanztypen m6id.xlarge, m6id.2xlarge, m6idn.xlarge und m6idn.2xlarge nicht für Hochleistungs- oder speicherintensive Workloads. Für diese Workloads verwenden Sie einen Instanztyp mit einer höheren Kernanzahl und mehr Arbeitsspeicher.

Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Unterstützte Konfigurationen für Cloud Volumes ONTAP in AWS"^].



== 3. Juni 2026



=== Lebenszyklusplanung



==== Aktualisierungen der Funktionsnamen für die Lebenszyklusplanung

Die folgenden Funktionen der Lebenszyklusplanung haben Namensänderungen erfahren:

* Die Funktion „Tech-Aktualisierung“ heißt jetzt *Systemaktualisierung*. Erfahren Sie, wie Sie link:../use/tech-refresh.html["eine Systemaktualisierung bewerten"].
* Die Funktion „Kapazitätserweiterungen“ heißt jetzt *Speichererweiterung*. Erfahren Sie, wie Sie link:../use/capacity-add.html["Speicherplatz erweitern"].
* Die Funktion „Verlängerungen“ heißt jetzt *Support Renewals*. Erfahren Sie, wie Sie link:../support/task-support-registration.html["Registrieren Sie sich für Support"].




=== Digitaler Berater



==== Aktualisierungen des Namens des Digital Advisor-Widgets

Die folgenden Digital Advisor-Funktionen haben Namensänderungen:

* Die Funktion „Tech-Aktualisierung“ heißt jetzt „Systemaktualisierung“. Erfahren Sie, wie Sie link:https://docs.netapp.com/us-en/active-iq/evaluate-tech-refresh.html["eine Systemaktualisierung bewerten"].
* Die Funktion „Kapazitätserweiterungen“ heißt jetzt „Speichererweiterung“. Erfahren Sie mehr über link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Digital Advisor Widgets"].
* Die Funktion „Verlängerungen“ heißt jetzt „Support-Verlängerungen“. Erfahren Sie mehr über link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Digital Advisor Widgets"].




== 26. Mai 2026



=== Ransomware-Resilienz



==== Google Cloud NetApp Volumes-Unterstützung (Vorschau)

Ransomware Resilience unterstützt jetzt die Erstellung von Schutzgruppen für Workloads in Google Cloud NetApp Volumes-Systemen, sodass Sie mehrere Workloads unter einer Richtlinie organisieren können, um die Verwaltung zu vereinfachen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Erstellen Sie eine Schutzgruppe in Ransomware Resilience"^].



== 25. Mai 2026



=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== Verbesserte Darstellung mehrerer Aktualisierungen am selben Tag in der Abonnement-Timeline

Die Abonnement-Zeitleiste zeigt nun eine Zahl an, wenn mehrere Abonnementaktualisierungen unterschiedlicher Art am selben Tag erfolgen, anstatt separater Symbole. Bewegen Sie den Mauszeiger über die Zahl, um alle Aktualisierungstypen dieses Tages anzuzeigen. Der heruntergeladene Bericht enthält für jede Aktualisierung eine separate Zeile und bietet Ihnen eine vollständige Übersicht aller Änderungen. Weitere Informationen finden Sie unter link:./integrations/subscription-timeline.html["Sehen Sie sich die Zeitleiste Ihrer Keystone Abonnements an"].



== 18. Mai 2026



=== Ransomware-Resilienz



==== Google Cloud NetApp Volumes-Unterstützung (Vorschau)

Ransomware Resilience unterstützt jetzt Google Cloud NetApp Volumes-Systeme und ermöglicht Ihnen so die effiziente Erkennung und Abwehr von Ransomware-Bedrohungen in Google Cloud NetApp Volumes. Bei der Erkennung zeigt Ransomware Resilience automatisch Workloads aus Google Cloud NetApp Volumes-Systemen an. Die erkannten Systeme werden im Ransomware Resilience-Dashboard angezeigt. Die Unterstützung für Google Cloud NetApp Volumes in Ransomware Resilience befindet sich derzeit in der Vorschauphase.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Erfahren Sie mehr über Ransomware Resilience"^]. Informationen zum Umfang der Google Cloud NetApp Volumes-Unterstützung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Einschränkungen der Ransomware-Resilienz"^].



==== Verbesserungen für Clean Restore

Die Funktion „Saubere Wiederherstellung“ unterstützt jetzt Berichte. Mithilfe von Berichten können Sie saubere Wiederherstellungen überprüfen und bewerten und diese Informationen offline als CSV-Datei speichern.

Die saubere Wiederherstellung unterstützt nun auch das Anhalten der Analyse. Wenn Sie die Analyse anhalten, müssen Sie die saubere Wiederherstellung erneut starten.

Weitere Informationen zu Berichten finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Berichte in Ransomware-Resilienz herunterladen"^]. Weitere Informationen zur Wiederherstellung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Stellen Sie Workloads mit einer sauberen Wiederherstellung wieder her"^].



=== Cloud Volumes ONTAP



==== Vereinfachte Cloud Volumes ONTAP-Bereitstellung in Azure

Mit Quick create können Sie Cloud Volumes ONTAP in Azure sowohl für Einzelknoten- als auch für Hochverfügbarkeitskonfigurationen (HA) bereitstellen. Dieser optimierte Prozess reduziert die Anzahl der Schritte im Vergleich zur fortschrittlichen Methoden, legt automatisch Standardwerte auf einer einzigen Seite fest und minimiert die Navigation, wodurch die Bereitstellung schneller und einfacher wird.

.Verwandte Links
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["Cloud Volumes ONTAP in Azure mit Schnellerstellung bereitstellen"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["Cloud Volumes ONTAP mit fortschrittlichen Methoden in Azure bereitstellen"^]




=== Digitaler Berater



==== Wellness-Überprüfung

Ab Juli 2026 ist die Funktion „Wellness-Überprüfung“ im Digital Advisor nicht mehr verfügbar. Bei Fragen senden Sie bitte eine E-Mail an mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].



== 12. Mai 2026



=== Cloud Volumes ONTAP



==== Flexible Abrechnung für Cloud Volumes ONTAP und Datendienste in AWS

NetApp bietet erweiterte Abrechnungsoptionen für Ihre Cloud Volumes ONTAP-Abonnements in AWS, sodass Sie mehr Kontrolle darüber haben, wie Sie für Cloud Volumes ONTAP-Kapazität und NetApp-Datendienste wie NetApp Backup and Recovery bezahlen. Bisher wurden alle Cloud Volumes ONTAP- und Datendienste-Nutzungen gemeinsam über die NetApp Intelligent Services (NIS)-Auflistung im AWS Marketplace abgerechnet.

Aufgrund von Änderungen im AWS Enterprise Discount Program (EDP) hat NetApp ein eigenständiges Cloud Volumes ONTAP-Abonnement im AWS Marketplace eingeführt, das es Ihnen ermöglicht, die Abrechnung der Cloud Volumes ONTAP-Kapazität von den Datendiensten zu trennen. Diese Trennung bietet Ihnen mehr Flexibilität bei der Verwaltung Ihrer EDP-Guthaben und -Kosten. NetApp empfiehlt die Nutzung des eigenständigen Abonnements für ein besseres Kostenmanagement Ihrer Cloud Volumes ONTAP Nutzung, während Sie das NIS-Abonnement weiterhin für die Abrechnung von Datendiensten nach dem 31. Juli 2026 verwenden sollten, wenn die EDP-Anforderungen in Kraft treten.

Das eigenständige Cloud Volumes ONTAP-Abonnement in AWS unterstützt ausschließlich gültige kapazitätsbasierte Essentials- oder Freemium-Lizenzpakete. Das Professional-Paket wird nicht unterstützt. Sie können die für Ihre Bedürfnisse optimale Abrechnungsmethode auswählen:

* *Eigenständiges Cloud Volumes ONTAP-Abonnement (Empfohlen)*: Bezahlen Sie Ihre Cloud Volumes ONTAP-Nutzung über das eigenständige Abonnement im AWS Marketplace, während die Datendienste weiterhin über das NIS-Abonnement abgerechnet werden. Dies ist die empfohlene Option für die meisten Kunden, die sowohl ein eigenständiges als auch ein NIS-Abonnement mit ihrem AWS-Konto in der NetApp Console verknüpft haben.
* *Kombiniertes NIS-Abonnement*: Bezahlen Sie sowohl Cloud Volumes ONTAP als auch Datendienste gemeinsam über den bestehenden NIS-Eintrag. Der kombinierte Ansatz gilt für Bestandskunden, die ausschließlich NIS-Abonnements mit ihrem AWS-Konto in der NetApp Console verknüpft haben. Allerdings empfiehlt NetApp, dass Sie Ihre Abrechnungspräferenz für Ihre Cloud Volumes ONTAP Nutzung festlegen und für eine bessere Kostenkontrolle auf das eigenständige Abonnement umsteigen.


Je nach Abonnementtyp ergeben sich folgende Szenarien:

.Nur Einzelabonnement (für Neukunden)
Wenn Sie in der NetApp Console nur ein eigenständiges AWS-Abonnement mit Ihrem AWS-Konto verknüpft haben und keine NIS-Abonnements besitzen, können Sie bei der Bereitstellung nur das Essentials-Lizenzpaket auswählen. Die Datenservices-Option *Backup und Recovery* steht Ihnen nicht zur Verfügung.

.Sowohl Einzelabonnements als auch NIS-Abonnements (für Bestandskunden)
Wenn Sie sowohl NIS- als auch eigenständige Abonnements mit Ihrem AWS-Konto verknüpft haben und keine Abrechnungspräferenz über die Registerkarte *Abrechnungseinstellungen* in der NetApp Console festgelegt haben, wird die Nutzung von Cloud Volumes ONTAP weiterhin standardmäßig über NIS abgerechnet. Dies ist auch die Standardeinstellung für jede Cloud Volumes ONTAP Instanz mit dem Professional-Paket, da das eigenständige Angebot Professional nicht unterstützt. Sie können eine Abrechnungspräferenz festlegen und auswählen, wie jeder Dienst abgerechnet wird:

* Legen Sie das Einzelabonnement als bevorzugtes Abrechnungskonto für Cloud Volumes ONTAP (mit Essentials-Paket) fest. Wenn Sie nur das Professional-Paket besitzen, können Sie es in ein Essentials-Paket umwandeln und Ihre Cloud Volumes ONTAP-Nutzung über die entsprechende Abrechnungseinstellung abrechnen. Wir empfehlen diese Vorgehensweise, da Sie so Ihre Cloud Volumes ONTAP EDP-Guthaben effizienter verwalten können.
* Nutzen Sie das NIS-Abonnement für die Abrechnung von Datendiensten oder die Nutzung von Cloud Volumes ONTAP über das Professional-Paket. Aktivieren Sie während der Bereitstellung den Datendienst *Backup und Recovery* und wählen Sie das Professional-Lizenzpaket aus, um Datendienste über das NIS-Abonnement abzurechnen.


.Nur NIS-Abonnement (Bestandskunden)
Dies gilt, wenn Sie bereits Kunde sind und NIS-Abonnements mit Ihrem AWS-Konto verknüpft haben. Sie können Cloud Volumes ONTAP und Datendienste weiterhin wie bisher gemeinsam abrechnen. Allerdings empfiehlt NetApp, für eine bessere Kostenkontrolle Ihrer Cloud Volumes ONTAP-Nutzung auf das eigenständige Abonnementmodell umzusteigen:

* Abonnieren Sie einen neuen eigenständigen Eintrag im AWS-Portal.
* Verknüpfen Sie das eigenständige Abonnement mit Ihrem AWS-Konto.
* Stellen Sie Ihre Abrechnungspräferenz auf das Einzelabonnement für die Nutzung von Cloud Volumes ONTAP mit dem Essentials-Paket ein.
* (Falls zutreffend) Wandeln Sie Ihr Professional-Paket in ein Essentials-Paket um und legen Sie die Abrechnungseinstellungen fest.
* Die Abrechnung von Datendiensten erfolgt weiterhin über Ihr NIS-Abonnement.



NOTE: Es kommt nicht zu doppelter Messung, wenn Sie mehrere Abonnementtypen verwenden oder zwischen Angeboten migrieren.

.Verwandter Link
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-set-up-licensing-aws.html["Lizenzierung für Cloud Volumes ONTAP in AWS einrichten"^]
* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-capacity-licenses.html#change-charging-methods["Ändern Sie die Abrechnungsmethoden für Kapazitätslizenzen"^]




== 11. Mai 2026



=== Konsoleneinrichtung und -verwaltung



==== Console Agent 4.7.0

Die Version 4.7.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Console-Agenten enthält Sicherheitsverbesserungen und Fehlerbehebungen.



==== NetApp Console

Diese Version enthält die folgende neue Funktion.

.Überprüfen Sie Ihre Console-Organisation
Standardmäßig zeigt Digital Advisor alle NetApp Konten an, die mit Ihrem Unternehmen verknüpft sind, und nicht nur Ihre Console-Organisation. Um die Anzeige in Digital Advisor auf ein bestimmtes Konto zu beschränken, verifizieren Sie das Geschäftskonto, das Sie mit Ihrer Console-Organisation verwenden möchten. link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-organization-verify.html["Erfahren Sie, wie Sie Ihre Console-Organisation überprüfen können."^]



=== Sicherung und Wiederherstellung



==== Hyper-V-Workload-Verbesserungen

In dieser Version werden für Hyper-V-Workloads die folgenden Verbesserungen eingeführt:

* *VMs auf SAN-Speicher schützen*: Sie können jetzt VMs auf SAN-Objektspeicher schützen.
* *Verbesserungen bei der Wiederherstellung an alternativen Speicherorten*: Sie können jetzt von primären und sekundären Speicherorten für VMs auf SAN-Speicher an einem alternativen Speicherort wiederherstellen.
* *Dateien und Ordner in einer Gast-VM*: Sie können jetzt Dateien und Ordner aus einem Snapshot auf dem primären Speicher in einer Gast-Windows-VM wiederherstellen. Diese Funktion wird nur für CIFS-VMs unterstützt.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Übersicht zum Schutz von Hyper-V-Workloads"].



==== Verbesserungen für KVM-Workloads

In dieser Version wird für KVM-Workloads die folgende Verbesserung eingeführt:

*Wiederherstellung an alternativem Speicherort*: Sie können KVM-VMs jetzt an einem alternativen Zielort wiederherstellen (diese Funktion ist jetzt allgemein verfügbar).

Weitere Informationen zum Schutz von KVM-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Übersicht über den Schutz von KVM-Workloads"] .



==== Verbesserungen der Oracle Database Workloads

In dieser Version werden die folgenden Verbesserungen für Oracle Database workloads eingeführt:

* *Unterstützung für Oracle AI Database 26ai*: Backup und Recovery unterstützen jetzt Oracle AI Database 26ai.
* *Unterstützung für die Backup-Verifizierung*: Sie können jetzt Backup-Richtlinien konfigurieren, um die Integrität Ihrer Oracle Datenbank-Backups automatisch zu überprüfen.


Weitere Informationen zum Schutz von Oracle Database-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Übersicht zum Schutz von Oracle Database-Workloads"].



==== VMware-Workload-Verbesserungen

In dieser Version führt VMware workloads die folgenden Verbesserungen ein:

* *Unterstützung für datenspeicherübergreifende Schutzgruppen*: Sie können nun das Verhalten von Schutzgruppen beim Schutz virtueller Maschinen auswählen, deren virtuelle Festplatten sich über mehrere Datenspeicher erstrecken.
* *Klonunterstützung*: Sie können jetzt Klone von Snapshots virtueller Maschinen aus dem primären und sekundären Speicher erstellen.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.05.1*: Diese Version enthält Trident Protect 26.05.1.
* *Wiederherstellung direkt am Ort für VM-basierte Anwendungen*: Sie können VM-basierte Anwendungen jetzt im ursprünglichen Namespace und ursprünglichen Cluster wiederherstellen.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



=== Datenklassifizierung



==== Verbesserte Konfigurationsseite

Die Datenklassifizierung hat die Konfigurationsseite aktualisiert und verbessert, wodurch die Verwaltung von Einstellungen, Systemen, das Aktivieren von Scans und die Überwachung des Systemzustands benutzerfreundlicher gestaltet werden können. Die neue Konfigurationsseite bietet die bestehenden Funktionen in einem übersichtlicheren Format und ermöglicht zusätzlich das Filtern von Systemen nach Typ, Fehlerstatus und Scanstatus. Die neue Seite bietet außerdem eine Zusammenfassung der verbundenen Systeme sowie Übersichten über aktive und konfigurierte Scans.

Überprüfen Sie eine link:https://youtu.be/_8YJ3KyZ7nI["Video-Anleitung"^]. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Scannen Sie Datenquellen mit Data Classification"^].



==== Compliance-Administrator-IAM-Rolle

Data Classification unterstützt jetzt eine Compliance-Administratorrolle zur Verwaltung von Berechtigungen in Data Classification. Die Compliance-Administratorrolle hat keinen Zugriff auf Ressourcen, einschließlich Konsolenagenten und Arbeitsbereichen. Benutzer mit der Compliance-Administratorrolle müssen mindestens einer weiteren Rolle zugeordnet sein.

Bei der Installation der Data Classification sollten Sie entweder die Rolle eines Console Platform Admin oder die Compliance Admin Rolle haben.

Wenn Sie bereits ein Benutzer sind, sollte der Zugriff wie gewohnt weiterlaufen. Beispielsweise hat eine Plattformrolle mit einer Ordner- oder Projektadministratorrolle bereits bestehenden Zugriff.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Datenklassifizierungsrollen"^].



==== Datenklassifizierung mit OVA implementieren

NetApp Data Classification unterstützt jetzt die Bereitstellung mit VMware Open Virtual Appliance (OVA) und bietet eine vereinfachte Bereitstellungsstrategie für lokale VMware vSphere-Umgebungen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Datenklassifizierung mit OVA implementieren"^].



=== Notfallwiederherstellung



==== Unterstützung für Kubernetes-basierte Workloads (Vorschau)

NetApp Disaster Recovery unterstützt jetzt auch Kubernetes-basierte Workloads. Mit Kubernetes-Unterstützung können Sie Anwendungen schützen, die auf Kubernetes-Clustern laufen, einschließlich OpenShift Virtualisierungsumgebungen. Disaster Recovery unterstützt link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["jede derzeit von Trident Protect unterstützte Kubernetes-Version"^], was eine nahtlose Integration und robuste Disaster-Recovery-Funktionen für containerisierte Anwendungen gewährleistet.

Hauptmerkmale der Kubernetes-basierten Workload-Unterstützung:

* **Umfassende Kompatibilität**: Disaster Recovery unterstützt alle mit Trident Protect kompatiblen Kubernetes-Versionen, einschließlich Red Hat OpenShift Virtualization.
* **Anwendungszentrierter Schutz**: Sie können Kubernetes-Workloads jetzt auf Anwendungsebene schützen und so die Wiederherstellung kritischer Dienste bei Failover-Ereignissen sicherstellen.
* **Vereinfachte Orchestrierung**: Disaster Recovery bietet intuitive Workflows zur Automatisierung der Sicherung und Replikation von Kubernetes-Workloads und nutzt dabei dieselbe effiziente SnapMirror-Technologie wie in VMware-Umgebungen.


Die Unterstützung für Kubernetes-basierte Workloads befindet sich derzeit in der Vorschauphase. Um mit dem Schutz von Kubernetes-basierten Workloads zu beginnen, siehe link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html["Kubernetes-Anforderungen für NetApp Disaster Recovery"^].



=== Ransomware-Resilienz



==== Verbesserungen für Clean Restore

Die Funktion „Saubere Wiederherstellung“ unterstützt jetzt die Wiederherstellung an einem alternativen Speicherort, sodass Sie Volumes auf verschiedenen Systemen, Speicher-VMs und Aggregaten wiederherstellen können, die vom selben Console-Agenten verwaltet werden. Außerdem wurde die Sieben-Tage-Beschränkung für die Suche nach geeigneten Snapshots für die Wiederherstellung aufgehoben. Die Funktion „Saubere Wiederherstellung“ durchsucht nun weiterhin alle verfügbaren Snapshots nach einem geeigneten Wiederherstellungspunkt, unabhängig vom Abstand zum Ransomware-Ereignis.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Stellen Sie Workloads mit einer sauberen Wiederherstellung wieder her"^].



==== Google SecOps SIEM-Unterstützung

Ransomware Resilience unterstützt jetzt Security Information and Event Management (SIEM) mit Google SecOps, wodurch Sie Daten automatisch an Google SecOps senden können, um die Bedrohungsanalyse und -erkennung zu optimieren.

Informationen zur Konfiguration finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Verbinden Sie NetApp Ransomware Resilience mit einem SIEM"^].



==== Azure NetApp Files-Unterstützung ist jetzt allgemein verfügbar

Ransomware Resilience unterstützt jetzt Azure NetApp Files-Systeme und ermöglicht Ihnen so die effiziente Erkennung und Abwehr von Ransomware-Bedrohungen in Azure NetApp Files. Bei der Erkennung von Workloads zeigt Ransomware Resilience nun Azure NetApp Files im Schutz-Dashboard an. Die Unterstützung von Ransomware Resilience für Azure NetApp Files umfasst Erkennungs- und Schutzstrategien, die ausschließlich auf Snapshots basieren. Die Unterstützung für Azure NetApp Files ist ab sofort allgemein verfügbar (GA).

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Erfahren Sie mehr über Ransomware Resilience"^].



==== SOAR-Unterstützung für das Blockieren von Benutzern

Ransomware Resilience unterstützt jetzt das Blockieren einzelner Nutzer mit Google SecOps und Splunk SOAR Playbooks. Mit dieser Erweiterung können Sie das Blockieren von Nutzern automatisieren, wenn Ransomware Resilience verdächtige Nutzeraktivitäten wie einen Datenverstoß oder massenhafte Datenlöschungen erkennt.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integrieren Sie ein SOAR-Playbook"^].



== 05. Mai 2026



=== Sicherung und Wiederherstellung



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.05*: Diese Version enthält Trident Protect 26.05.
* *Upgrade Trident Protect von Backup und Recovery*: Wenn auf Ihrem Kubernetes-Cluster Trident Protect 26.05 oder neuer ausgeführt wird, können Sie Trident Protect jetzt direkt von Backup und Recovery aus aktualisieren.
* *Native Unterstützung für den Schutz von VMs*: Sie können jetzt VM-basierte Anwendungen erstellen, mit denen Sie virtuelle Maschinen genauso schützen können wie jede andere Anwendung.
* *Ressourcentransformationen*: Sie können jetzt Ressourcentransformationen und Ressourcentransformationsvorlagen verwenden, um während des Wiederherstellungsprozesses Ressourcenattribute hinzuzufügen, zu entfernen und zu ändern.
* *Geschützte Ressourcen anzeigen*: Sie können nun die in jedem Wiederherstellungspunkt einer Anwendung enthaltenen Ressourcen anzeigen und einen detaillierten JSON-Bericht herunterladen. Dies gibt Ihnen vollständige Transparenz über Ihre Wiederherstellungspunkte und vereinfacht die Audit-Compliance.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



== 27. April 2026



=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== Umbenanntes Label für bereitgestellte Kapazität

Die Bezeichnung *Bereitgestellte Kapazität* wurde in *Bereitgestellte Volumenkapazität* umbenannt. Die aktualisierte Bezeichnung wird auch in den zugehörigen CSV- und Excel-Berichten berücksichtigt.



==== Prognoseumschalter für aufgelaufene Burst-Nutzung

Sie können jetzt die *Prognose*-Funktion in der Ansicht *Aufgelaufener Burst* auf der Registerkarte *Verbrauchstrend* nutzen, um den aufgelaufenen Burst-Verbrauch für die nächsten 120 Tage ab dem aktuellen Datum zu prognostizieren. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-forecast-data["Prognosedaten anzeigen"].



== 20. April 2026



=== Sicherung und Wiederherstellung



==== VMware-Workload-Verbesserungen

In dieser Version führt VMware Workloads die folgende Verbesserung ein:

*ASA r2 SAN-Unterstützung*: VMware-Workloads unterstützen jetzt den Schutz von VMs auf VMFS-Datenspeichern, die in NetApp ASA r2 SAN-only-Umgebungen gehostet werden.

Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



== 13. April 2026



=== Konsoleneinrichtung und -verwaltung



==== Console Agent 4.6.0

Die Version 4.6.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Console-Agenten enthält Sicherheitsverbesserungen und Fehlerbehebungen sowie die folgende neue Funktion.

.Unterstützung für Konfigurationsprüfungen des benötigten Speicherplatzes
Sie können mithilfe von Konfigurationsprüfungen sicherstellen, dass der für den Konsolenagenten erforderliche Speicherplatz verfügbar ist. Sie können Konfigurationsprüfungen von der Konsole oder der Wartungskonsole des Agenten aus durchführen. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html["Erfahren Sie mehr über die Durchführung von Konfigurationsprüfungen auf dem Konsolenagent."^]

.Aktualisieren Sie einen mit vCenter bereitgestellten Console-Agenten mithilfe einer ISO
Wenn Sie einen Console-Agenten in vCenter mithilfe einer OVA bereitgestellt haben, können Sie ihn jetzt auf eine neue Version aktualisieren, indem Sie eine ISO an die VM anhängen und das Upgrade von der VM-Wartungskonsole ausführen. link:https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-agent.html["Erfahren Sie, wie Sie einen vCenter-bereitgestellten Konsolenagenten aktualisieren"^]



=== Sicherung und Wiederherstellung



==== ONTAP Volumes Workloads-Verbesserungen

In dieser Version führt ONTAP Volumes-Workloads die folgende Verbesserung ein:

*NetApp MetroCluster Aktiv/Aktiv-Konfigurationen unterstützt*: NetApp Backup and Recovery for Volumes-Workloads unterstützt jetzt MetroCluster in der Aktiv/Aktiv-Konfiguration.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



==== Kubernetes-Workloads-Erweiterungen

In dieser Version führt Kubernetes-Workloads die folgenden Verbesserungen der Datensicherungsstrategie ein:

* *Bearbeitung der Schutzrichtlinien*: Sie können jetzt die Kubernetes-Workload-Schutzrichtlinien bearbeiten, falls Sie sie ändern müssen.
* *Disk-to-Disk-Unterstützung*: Sie können jetzt Kubernetes-Schutzrichtlinien mit einer Disk-to-Disk-Backup-Architektur konfigurieren.
* *Unterstützung für Google Cloud Platform storage bucket*: Sie können jetzt Kubernetes-Datensicherungsstrategien so konfigurieren, dass Backups in Google Cloud Platform storage buckets gespeichert werden.


Weitere Informationen zu den Datensicherungsstrategien finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-policies-create.html["Erstellen und Verwalten von Datensicherungsstrategien in NetApp Backup and Recovery"].

Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



==== Hyper-V-Workload-Verbesserungen

In dieser Version werden für Hyper-V-Workloads die folgenden Verbesserungen eingeführt:

* *Verbesserte Auftragsabwicklung*: Backup and Recovery verarbeitet jetzt mehrere gleichzeitig laufende Aufträge effizienter.
* *SAN-Unterstützung (Vorschau)*: Backup and Recovery unterstützt jetzt den Schutz von Hyper-V-VMs, die auf SAN-Speichern abgelegt sind.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Übersicht zum Schutz von Hyper-V-Workloads"].



==== Verbesserungen für KVM-Workloads

In dieser Version werden für KVM-Workloads die folgenden Verbesserungen eingeführt:

* *Verbesserte Auftragsabwicklung*: Backup and Recovery verarbeitet jetzt mehrere gleichzeitig laufende Aufträge effizienter.
* *Wiederherstellung an alternativem Speicherort (Vorschau)*: Sie können KVM-VMs jetzt an einem alternativen Ziel wiederherstellen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-restore.html["Stellen Sie KVM-VMs mit NetApp Backup and Recovery wieder her"].


Weitere Informationen zum Schutz von KVM-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Übersicht über den Schutz von KVM-Workloads"] .



==== VMware-Workload-Verbesserungen

In dieser Version führt VMware workloads die folgenden Verbesserungen ein:

* *Tagbasierter Schutz*: Backup and Recovery für VMware-Workloads unterstützt jetzt tagbasierten Schutz für VMs, die auf NFS- und VMFS-Volumes gespeichert sind, sodass Sie Schutzgruppen aus vCenter-Tags anstatt aus einzelnen VMs oder Datenspeichern erstellen können. Wenn Sie VMs und Datenspeicher in vCenter taggen, erkennt Backup and Recovery diese automatisch und schließt sie in zukünftige Backups ein, ohne dass eine manuelle Gruppenverwaltung erforderlich ist. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Schutzgruppen erstellen und verwalten"].
* *Wiederherstellung auf alternativem Speichersystem*: Sie können virtuelle Maschinen jetzt auch dann auf einem alternativen Speichersystem wiederherstellen, wenn das ursprüngliche (primäre) Speichersystem vollständig ausgefallen ist. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore.html["VMware-Workloads wiederherstellen"].
* *Dateien auf Linux-VMs wiederherstellen*: Sie können jetzt VM-Dateien und -Ordner auf Linux-VMs wiederherstellen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Dateien und Ordner wiederherstellen"].
* *Unterstützung für Proxy-VMs beim Wiederherstellen von Dateien und Ordnern* – Sie können jetzt Dateien und Ordner von virtuellen Festplatten mithilfe einer Proxy-VM wiederherstellen, wenn Sie die virtuelle Festplatte nicht an die ursprüngliche VM anbinden möchten. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Dateien und Ordner wiederherstellen"].
* *Rekursive Datei- und Ordnersuche* – Sie können jetzt eine gesamte virtuelle Festplatte nach einer bestimmten Datei oder einem bestimmten Ordner durchsuchen. Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Dateien und Ordner wiederherstellen"].
* *Verbesserte Auftragsabwicklung*: Backup and Recovery verarbeitet jetzt mehrere gleichzeitig laufende Aufträge effizienter.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



=== Datenklassifizierung



==== Allgemeine Verbesserungen

Diese Version der Datenklassifizierung enthält Fehlerbehebungen, Sicherheitsverbesserungen und Leistungsoptimierungen.



=== Cloud-Tiering



==== NetApp Cloud Tiering wird nicht mehr angeboten

NetApp Cloud Tiering ist ab dem 26. April 2026 nicht mehr zum Kauf oder zur Lizenzverlängerung verfügbar.

Bestehende Kunden können NetApp Cloud Tiering weiterhin nutzen und Support dafür erhalten, bis ihr Abonnement oder Lizenzvertrag abläuft. Nach Ablauf des Abonnements haben Kunden keinen Zugriff mehr auf die Funktionen oder den Support von NetApp Cloud Tiering.

NetApp empfiehlt Kunden, gemeinsam mit ihrem NetApp-Ansprechpartner ihre bestehenden Tiering-Lizenzen auf ONTAP FabricPool-Lizenzen umzustellen, die die Funktionalität für Data Tiering in ONTAP bereitstellen. Siehe link:https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html["Installieren einer FabricPool-Lizenz auf einem ONTAP Cluster"] für weitere Informationen zur Einrichtung von Data Tiering in ONTAP mit FabricPool.

* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-Notice2.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_9L2PauNXYE0fOs0RIz8KK2q5Jb6sg8Yv-97NNJ53ceAab9UAqpKOrAvByxsOWqhIQHNCHgFfM0q3TI["NetApp Cloud Tiering End-of-Availability-Benachrichtigung"]
* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-FAQ-v3.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_rplJe_ZtlY4PQAQRQlewsDa0W4JR55muT0KCThR46zI7-uOhIYfVsxODDKFrnYYvy5uZzvhEKHOwBI["NetApp Cloud Tiering FAQ zum Ende der Verfügbarkeit"]




=== Notfallwiederherstellung



==== Google Cloud VMware Engine (GCVE) wird ab sofort allgemein unterstützt (GA)

NetApp Disaster Recovery-Unterstützung für GCVE ist jetzt allgemein verfügbar (GA). Mit GA-Unterstützung unterstützt Disaster Recovery für GCVE jetzt:

* *Plattformverwaltete Snapshots:* Backups und Aufbewahrungsrichtlinien lassen sich nahtlos über ONTAP oder Google Cloud Platform (GCP) verwalten.
* *Mehrere Datenspeicher pro Replikationsplan:* Vereinfachen Sie Ihre Disaster Recovery-Pläne, indem Sie mehrere Datenspeicher in einer einzigen Replikationsstrategie konsolidieren.
* *Erzwingen eines Failovers bei nicht verfügbaren Quellstandorten:* Wechseln Sie zu einem Disaster Recovery-Standort, wenn die Quelle nicht verfügbar ist.
* *Die SnapMirror-Resynchronisierung aufschieben und die Replikation bei Bedarf wiederherstellen:* Schieben Sie SnapMirror-Resynchronisierungen auf, um Auswirkungen auf Produktions-Workloads während Spitzenbetriebszeiten mit der Option „skip protect“ zu vermeiden, und stellen Sie die Replikation später bei Bedarf mit der Option „re-protect“ wieder her.


Weitere Informationen zur Unterstützung von GCVE finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["Unterstützte Konfigurationen für die Notfallwiederherstellung"^].



=== Ransomware-Resilienz



==== Saubere Wiederherstellung

Ransomware Resilience unterstützt jetzt Clean Restores, eine neue Wiederherstellungsoption, mit der Sie sich schnell und einfach von Ransomware-Angriffen erholen können. Clean Restores bieten geführte Arbeitsabläufe, die optimale Wiederherstellungspunkte identifizieren, um Ihre Workloads wieder zum Laufen zu bringen und die Ausfallzeit zu minimieren. Die Arbeitsabläufe in Clean Restore bieten außerdem Einblicke auf Dateiebene in Ihre Daten, sodass Sie malwarefreie Workloads wiederherstellen können, was eine erneute Infektion verhindert und Datenverlust minimiert.

Informationen zu unterstützten Konfigurationen und zur Konfiguration Ihres Systems für eine vollständige Wiederherstellung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore.html["Erstellen Sie eine isolierte Wiederherstellungsumgebung"^]. Informationen zur Wiederherstellung mittels vollständiger Wiederherstellung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Stellen Sie Workloads mit einer sauberen Wiederherstellung wieder her"^].



==== SIEM-Unterstützung für Splunk Enterprise

Ransomware Resilience bietet jetzt Security Information Event Management (SIEM)-Unterstützung für Splunk Enterprise, wodurch Sie Protokoll- und Ereignisdaten zentralisieren und die Bedrohungsanalyse und -erkennung optimieren können.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Verbinden Sie NetApp Ransomware Resilience mit einem SIEM"^].



==== Verbesserung der Benutzerverhaltenserkennung

Erkenntnisse über Datenschutzverletzungen werden nun 13 Monate nach dem Vorfall gespeichert, wodurch eine längere Datenspeicherung für Ihre Berichtspflichten ermöglicht wird.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-user-behavior.html["Erfahren Sie mehr über die Erkennung des Nutzerverhaltens"^].

Replikation :leveloffset: +1



=== Replikationsmanagement für bestehende Beziehungen mit FSx für ONTAP

Die Replikationsbeziehungsverwaltung für FSx for ONTAP-Dateisysteme als Quelle oder Ziel befindet sich jetzt in NetApp Workload Factory.

link:https://docs.netapp.com/us-en/data-services-replication/task-managing-replication.html["Datenreplizierung verwalten"]



=== Cloud Volumes ONTAP



==== Verbesserte Cloud Volumes ONTAP Unterstützung mit Google Cloud C3 VMs

Cloud Volumes ONTAP bietet jetzt erweiterte Unterstützung für die Google Cloud C3-Serie VMs und ermöglicht diese zusätzlichen Funktionen:

* In Ihren Cloud Volumes ONTAP Bereitstellungen können Sie zwischen verschiedenen Instanztypen innerhalb der C3-Familie wechseln.
* Wenn Sie den Instanztyp ändern und c3-standard-44 oder c3-standard-88 sowie deren LSSD-Varianten als Ziel-VM auswählen, wird der Google Netzwerkservice Egress-Netzwerk-Tier Tier-1 automatisch angewendet. Wenn Sie zu einer anderen C3-Variante wechseln, wird das Egress-Netzwerk-Tier auf Standard gesetzt.
+

NOTE: Die Umstellung der Ausgangsnetzwerkebene auf Tier-1 verursacht zusätzliche Kosten. Planen Sie die Bereitstellung und das Upgrade entsprechend.

* Wenn Sie die lokalen SSD-Varianten (LSSD) von C3 auswählen, wird Flash Cache standardmäßig aktiviert. Sie können in Ihrer Cloud Volumes ONTAP Bereitstellung nicht zwischen den C3-LSSD-Varianten wechseln, selbst wenn die Zielvariante Flash Cache unterstützt.
* Auf Ihren C3-VMs können Sie jetzt sowohl neuen als auch bestehenden Aggregaten Volumes hinzufügen.
* Die IOPS- und Durchsatzeinstellungen können beim Hinzufügen von Volumes über die NetApp Console oder mithilfe der  `PUT /gcp/vsa/aggregates/{workingEnvironmentId}/{aggregateName}` API geändert werden.


.Verwandte Links
* https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Unterstützte Konfigurationen für Cloud Volumes ONTAP in Google Cloud"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#cloud-volumes-ontap-support-for-next-generation-google-cloud-vms["Cloud Volumes ONTAP Unterstützung für Google Cloud VMs der nächsten Generation"^]

