---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind. 
---
= Aktuelle Änderungen in der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind.  Eine vollständige Versionshistorie finden Sie unterlink:release-notes-index.html["Vollständiger Satz der Versionshinweise"] für jeden einzelnen Dienst.

[NOTE]
====
Die folgenden Dienste wurden eingestellt:

Edge-Caching:: Der Edge-Caching-Dienst wurde am 7. August 2024 entfernt.
Kubernetes:: Die Unterstützung für die Erkennung und Verwaltung von Kubernetes-Clustern wurde am 7. August 2024 entfernt.
Migrationsberichte:: Der Dienst für Migrationsberichte wurde am 7. August 2024 entfernt.
Betriebsstabilität:: Die Funktionen zur betrieblichen Ausfallsicherheit wurden am 22. August 2025 entfernt.
Sanierung:: Der Sanierungsdienst wurde am 22. April 2024 entfernt.


====


[[15-july-2026]]
== 15. Juli 2026



[[console-setup-and-administration]]
=== Konsoleneinrichtung und -verwaltung



==== Console Agent 4.9.0

Die Version 4.9.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Console-Agenten enthält Sicherheitsverbesserungen und Fehlerbehebungen.



==== NetApp Console

.Unterstützung für rollenbasierte Zugriffssteuerung für Cloud Volumes ONTAP
Die Konsole unterstützt rollenbasierte Zugriffssteuerung für Cloud Volumes ONTAP.

link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["Weitere Informationen über rollenbasierte Zugriffssteuerung für Cloud Volumes ONTAP"^].



[[amazon-fsx-for-ontap]]
=== Amazon FSX für ONTAP



==== GenAI-Workload-Entfernung aus den Workloads in der NetApp Console

Die GenAI-Workload wurde aus Workloads in der NetApp Console entfernt.



[[14-july-2026]]
== 14. Juli 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Cloud Volumes ONTAP 9.19.1 RC

Die NetApp Console kann jetzt verwendet werden, um die Release Candidate (RC) Version von Cloud Volumes ONTAP 9.19.1 in Google Cloud bereitzustellen und zu verwalten. Diese Version ist für die Bereitstellung und das Upgrade in Amazon Web Service (AWS) und Microsoft Azure (Azure) nicht verfügbar.

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["Weitere Informationen zu dieser Version von Cloud Volumes ONTAP"^].



==== Unterstützung für Google Cloud VMs der nächsten Generation in Cloud Volumes ONTAP HA

Mit Version 9.19.1 wechselt NetApp die Cloud Volumes ONTAP Hochverfügbarkeitsbereitstellungen (HA) von N2 VMs auf die VMs der nächsten Generation der Google Cloud C3-Serie für eine schnellere und skalierbare Benutzererfahrung.


NOTE: Diese Unterstützung gilt nur für HA-Bereitstellungen mit einer einzelnen Verfügbarkeitszone (AZ).

Sie können jetzt die Vorteile von VMs der C3-Serie beim Einsatz von Cloud Volumes ONTAP 9.19.1 und höher in Google Cloud nutzen. Diese Maschinen bieten verbesserte Leistung und höhere Kapazitätsgrenzen. Sie verwenden Google Virtual NIC (gVNIC) und Hyperdisk Balanced Festplatten für dynamische Leistung bei intensiven Workloads.

Wenn auf Ihrem Cloud Volumes ONTAP System Version 9.19.1 oder höher ausgeführt wird, verwenden die vorkonfigurierten Pakete, die für einfache Bereitstellungen in einzelnen Verfügbarkeitszonen genutzt werden, automatisch C3 VMs, wobei Sie die IOPS- und Durchsatzparameter entsprechend Ihren Workload-Anforderungen anpassen können. Ebenso kann beim Erstellen von Aggregaten Zonal Hyperdisk Balanced Disks hinzugefügt werden, um in Google Cloud eine bessere Leistung und Skalierbarkeit zu erreichen. Es kann außerdem die LSSD-Variante der C3-Serie Maschinen für die standardmäßige Flash Cache-Unterstützung ausgewählt werden.

Folgende Punkte sind zu beachten:

* In Ihren Cloud Volumes ONTAP Bereitstellungen können C3-VMs nicht in VMs der N2-Serie und umgekehrt geändert werden. Es ist jedoch möglich, innerhalb der C3-Familie zwischen verschiedenen Instanztypen zu wechseln.
+

NOTE: Das Ändern des Instanztyps innerhalb der C3-Familie kann je nach Anzahl der angeschlossenen Datenträger länger dauern. Eine frühzeitige Planung der Konfiguration hilft, Leistungseinbußen zu vermeiden.

* Beim Ändern des Instanztyps wird, wenn c3-standard-44 oder c3-standard-88 sowie deren lokale SSD (LSSD)-Varianten als Ziel-VM ausgewählt werden, der Google Netzwerkservice Egress Network Tier _Tier-1_ automatisch angewendet. Bei einem Wechsel zurück zu einer anderen C3-Variante wird die Egress Network Tier auf _Standard_ gesetzt.
+

NOTE: Die Umstellung der Ausgangsnetzwerkebene auf Tier-1 verursacht zusätzliche Kosten. Die Bereitstellung und das Upgrade sollten entsprechend geplant werden.

* Wenn Sie die LSSD-Varianten von C3 auswählen, wird Flash Cache standardmäßig aktiviert. Ein Wechsel zwischen den C3 LSSD-Varianten ist in Ihrer Cloud Volumes ONTAP Bereitstellung nicht möglich, selbst wenn die Zielvariante Flash Cache unterstützt.
* Auf Ihren C3 VMs können sowohl neuen als auch bestehenden Aggregaten Volumes hinzugefügt werden.
* Bei der Replikation eines Cloud Volumes ONTAP Systems mit einem VM-Typ N2 auf einen VM-Typ C3 wird der Festplattentyp standardmäßig auf Hyperdisk Balanced eingestellt.
* Die IOPS- und Durchsatzeinstellungen können beim Hinzufügen von Aggregaten über die NetApp Console oder mithilfe der  `PUT /gcp/ha/aggregates/{workingEnvironmentId}/{aggregateName}` API geändert werden.


https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Unterstützte Konfigurationen für Cloud Volumes ONTAP in Google Cloud"^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series["Google documents: C3-Maschinenserie"^]



==== Vereinfachte Cloud Volumes ONTAP Bereitstellung in Google Cloud

Mit dem *Quick create*-Assistenten kann Cloud Volumes ONTAP in Google Cloud sowohl für Single-Node- als auch für High-Availability-(HA)-Konfigurationen bereitgestellt werden. Dieser optimierte Prozess reduziert die Schritte, legt Standardwerte automatisch auf einer einzigen Seite fest und minimiert die Navigation für eine schnellere und einfachere Bereitstellung.

.Verwandte Links
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-gcp.html["Cloud Volumes ONTAP in Google Cloud mit Quick create bereitstellen"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-gcp.html["Cloud Volumes ONTAP mit fortschrittlichen Optionen in Google Cloud bereitstellen"^]




==== Einführung von Zugriffsrollen für Cloud Volumes ONTAP

NetApp führt Identity and Access Management (IAM)-Rollen für Cloud Volumes ONTAP ein, wodurch rollenbasierte Zugriffssteuerung (RBAC) für mehr Sicherheit und einfachere Compliance ermöglicht wird. Benutzer können sich weiterhin mit ihren bestehenden Anmeldeinformationen für Cloud Volumes ONTAP-Operationen an der NetApp Console anmelden. Die Authentifizierung wird nun jedoch über die Identitätsföderation geleitet, sodass der Konsolenadministrator eine detailliertere Kontrolle über diese Funktionen erhält. Jeder Benutzer muss eine der folgenden Rollen besitzen, um eine beliebige Operation in Cloud Volumes ONTAP auszuführen. Ohne eine Rolle können Benutzer keine Cloud Volumes ONTAP Instanzen anzeigen oder darauf zugreifen.

* *Cloud Volumes ONTAP viewer*: Gewährt schreibgeschützten Zugriff auf die Bildschirme und Registerkarten von Cloud Volumes ONTAP. Bestimmte Bildschirme und Aktionsschaltflächen sind in dieser Rolle deaktiviert.
* *Cloud Volumes ONTAP Operator*: Ermöglicht alltägliche Verwaltungsaufgaben, wie das Hinzufügen von Volumes, die Verwaltung von Speicher und die Konfiguration der Replikation.
* *Cloud Volumes ONTAP Admin*: Bietet vollständigen Zugriff auf alle Cloud Volumes ONTAP Operationen.


Der Konsolenadministrator weist Cloud Volumes ONTAP Benutzern unter *Administration > Identity* Rollen zu. Die Rollenberechtigungen basieren auf der Organisation des Benutzers und gelten für alle Cloud Volumes ONTAP Systeme innerhalb dieser Organisation.

Cloud Volumes ONTAP setzt rollenbasierte Zugriffssteuerung (RBAC) mithilfe eines lokalen Caches der Berechtigungen jedes Benutzers durch, der automatisch einmal pro Stunde aktualisiert wird. Wenn einem Benutzer eine neue Rolle zugewiesen wird oder seine bestehende Rolle geändert wird, kann es bis zu einer Stunde dauern, bis diese Änderung wirksam wird. Danach sind alle durch die Rollen erlaubten Workflows aktiviert.


NOTE: Bei der erstmaligen Bereitstellung eines Console Agenten oder beim Upgrade eines bestehenden Console Agenten auf Console 4.9.0 oder höher werden in einem einmaligen Initialisierungsprozess automatisch Cloud Volumes ONTAP Rollen allen vorhandenen Benutzern in der Organisation zugewiesen. Dieser Vorgang kann bis zu 30 Minuten dauern. Nach Abschluss weist die Console den vorhandenen Benutzern die entsprechenden Rollen zu.

Cloud Volumes ONTAP Rollen gelten für Amazon Web Service (AWS), Microsoft Azure (Azure) und Google Cloud Umgebungen.

.Verwandte Links
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["NetApp Console-Zugriffsrollen"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["Cloud Volumes ONTAP Zugriffsrollen in der NetApp Console"^]




[[13-july-2026]]
== 13. Juli 2026



[[backup-and-recovery]]
=== Sicherung und Wiederherstellung



==== ONTAP Volumes Workloads-Verbesserungen

In dieser Version führt ONTAP Volumes-Workloads die folgende Verbesserung ein:

*Verbesserte Unterstützung für mehrere Buckets*: Ab ONTAP 9.19.1 und neueren Versionen ist es möglich, die Volumes innerhalb eines Systems mit bis zu 100 Buckets pro System über verschiedene Cloud-Anbieter hinweg zu schützen.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



[[disaster-recovery]]
=== Notfallwiederherstellung



==== Kubernetes-Updates

Die Notfallwiederherstellung hat die folgenden Änderungen für Kubernetes-basierte Workloads eingeführt:



===== Trident Protect über das Menü „Standorte“ verwalten

Disaster Recovery unterstützt jetzt die direkte Verwaltung von Trident Protect über das Menü „Sites“ in der Disaster Recovery-Benutzeroberfläche. Trident Protect kann aktualisiert oder aus Disaster Recovery entfernt werden, wodurch die Verwaltung Ihrer Kubernetes-Ressourcen vereinfacht wird.

Weitere Informationen finden sich unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Standorte verwalten"^].



==== VMware-Updates

Die Notfallwiederherstellung hat die folgenden Änderungen für VMware basierte Workloads eingeführt:



===== Failover bei leeren Datenspeichern

Replikationspläne mit leeren Datenspeichern können nun erfolgreich per Failover übernommen werden, ohne dass diese aus dem Plan ausgeschlossen oder ein Failover erzwungen werden muss. Während des Failovers bindet Disaster Recovery den leeren Datenspeicher automatisch am Disaster Recovery-Standort ein, sodass VMs hinzugefügt und für Failback-Operationen geschützt werden können.

Weitere Informationen finden sich unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Failover zu einem Remote-Standort"^].



===== vCenter Netzwerkautomapping

Netzwerkzuordnungen können nun auf vCenter-Ebene (also außerhalb des Dialogfelds für Replikationspläne) konfiguriert werden. Nach der Konfiguration wendet Disaster Recovery diese Netzwerkzuordnungen beim Hinzufügen oder Bearbeiten eines Replikationsplans automatisch an, was die Verwaltung von Replikationsplänen vereinfacht.

Die Notfallwiederherstellung unterstützt weiterhin planbezogene Überschreibungen. Bestehende Netzwerkzuordnungen, die innerhalb eines Replikationsplans definiert sind, können weiterhin netzwerkbezogen bearbeitet werden; diese Zuordnungen haben Vorrang vor den vCenter-Definitionen auf Netzwerkebene.



==== Einschränkung der Disaster Recovery Viewer-Rolle

Die Möglichkeit, die Registerkarte „Upgrade System“ anzuzeigen, wurde aus der Rolle „Disaster Recovery viewer“ entfernt. Diese Änderung stimmt die Rolle besser auf die angemessene Erfahrung für Benutzer mit Nur-Lesezugriff ab. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Informationen zu Benutzerrollen und Berechtigungen in NetApp Disaster Recovery"^].



==== Systemleistungsverbesserungen

Disaster Recovery hat Änderungen eingeführt, um den Systemressourcenverbrauch zu reduzieren und die Leistung bei allen Vorgängen zu verbessern.



[[07-july-2026]]
== 07. Juli 2026



[[ransomware-resilience]]
=== Ransomware-Resilienz



==== Dateipfade von Benachrichtigungen zum Benutzerverhalten ausschließen

NetApp Ransomware Resilience unterstützt das Ausschließen bestimmter Dateipfade von Warnmeldungen zur Überwachung des Benutzerverhaltens. Dateipfade können ausgeschlossen werden, wenn bekannt ist, dass sie nicht gefährdet sind, oder wenn an Dateien in einem Volume gearbeitet wird, das möglicherweise Warnmeldungen auslösen könnte.

Weitere Informationen finden sich unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html["Dateipfade von Benachrichtigungen ausschließen"^].



==== ARM Vorlage für Microsoft Sentinel

Ransomware Resilience bietet jetzt eine Azure Resource Manager (ARM) Vorlage für die Verbindung mit Microsoft Sentinel als SIEM und bietet eine zusätzliche Methode zur Vereinfachung der Bereitstellung.

Weitere Informationen finden sich unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Anbindung an ein SIEM-System zur Bedrohungserkennung und -analyse"^].



[[29-june-2026]]
== 29. Juni 2026



[[ransomware-resilience]]
=== Ransomware-Resilienz



==== Automatisierte Antworten auf Benachrichtigungen zu Benutzeraktivitäten

Ransomware Resilience unterstützt jetzt die Automatisierung der Snapshot-Erstellung und das Sperren von Benutzern, wenn eine Benutzeraktivitätswarnung generiert wird. Mit automatisierten Reaktionen lässt sich ein Benutzer unmittelbar nach Generierung einer Warnung sperren und ein Snapshot zur Wiederherstellung erstellen, was eine schnellere Reaktion ohne manuelle Eingriffe ermöglicht.

Weitere Informationen sind unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-automate-user-activity.html["Antworten auf Warnmeldungen zu Benutzeraktivitäten automatisieren"^] zu finden.



[[digital-advisor]]
=== Digitaler Berater



==== Health Check GraphQL Migration und Verbesserungen der Datengenauigkeit

Das Modul „Health Check“ wurde mit verbesserter Datengenauigkeit und Versionsempfehlungen gemäß Währungsstandards erweitert. Im Rahmen dieser Version wurde es von der Public API zu GraphQL migriert, was eine verbesserte Performance, flexible Abfragen und langfristigen Support bietet.



===== Empfohlene Software

Empfohlene Software-Erweiterungen im Modul Health Check liefern nun genauere und konsistentere Daten.

* Die Anzahl der Regale und Laufwerke unter der Firmware-Währung zeigt die genauen Werte pro System an und schließt die Anzahl der HA-Paare nicht mehr ein.
* Die Empfehlungen für die Mindest- und die neueste Version werden nun auf Clusterebene auf Basis der effektiven Clusterversion gemäß den aktuellen Währungsstandards berechnet, zuvor wurden diese Empfehlungen auf Knotenebene berechnet.




===== AutoSupport Datenabhängigkeit

Aufgrund von Verbesserungen im Backend basieren die Ansichten zur AutoSupport-Adoption und zu empfohlenen Softwareversionen auf den neuesten AutoSupport-Daten. Dies kann Ihre aktuelle Ansicht wie folgt beeinflussen:

[cols="30,70"]
|===
| Szenario | Betroffene Systeme 


| Es werden keine Daten angezeigt | Systeme, die seit Oktober 2025 keine AutoSupport-Nachricht mehr gesendet haben 


| Veraltete Werte | Systeme, die in den letzten 30 Tagen keinen AutoSupport gesendet haben 
|===
Lösen Sie AutoSupport auf den oben aufgeführten betroffenen Systemen erneut aus, um die aktuellen Daten in den Health-Check-Ansichten wiederherzustellen.



[[keystone]]
=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== ADP-Lizenzverteilung für MetroCluster Abonnements anzeigen

Auf der Registerkarte *Erweiterter Datenschutz (ADP)* ist jetzt ein neuer Unterreiter *Lizenzverteilung* verfügbar, der Einblick in die ADP-Lizenznutzung in Ihren MetroCluster Partnerclustern bietet. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/keystone-staas/integrations/adp-tab.html["Verbrauch und Status Ihrer Keystone MetroCluster Abonnements einsehen"].



==== Ransomware-Schutzstatus für Ihre Volumes

Die Registerkarte *Volumes in Clustern* unter *Assets* enthält jetzt eine Spalte *ARP-Status*, die anzeigt, ob der Autonomous Ransomware Protection (ARP) für jedes Volume aktiviert oder deaktiviert ist und Ihnen so einen Überblick über Ihre Ransomware-Schutzmaßnahmen für alle verwalteten Assets gibt. Weitere Informationen zu ARP finden sich unter https://docs.netapp.com/us-en/ontap/anti-ransomware/["Autonomous Ransomware Protection (ARP) in ONTAP"^].



==== Feedback kann über die Registerkarte „Feedback“ geteilt werden.

Sie können nun von jedem Bildschirm im Keystone Dashboard aus Feedback geben, indem Sie die neue Registerkarte *Feedback* verwenden, die am unteren rechten Bildschirmrand verankert ist. Ein Klick darauf öffnet ein Fenster, in dem Sie Ihre Erfahrungen mitteilen und Kommentare direkt an NetApp senden können.



==== Verbesserte Benachrichtigungen für Kapazitätsauslastung und Abonnementablauf

Systemgenerierte Monitore bieten jetzt detailliertere Warnmeldungen zur Kapazitätsauslastung und zum Ablauf von Abonnements.

Bei Ablauf des Abonnements werden nun Warnungen bei fünf Schwellenwerten ausgelöst: 180, 90, 60, 30 und 7 Tage vor Ablauf, wobei der Schweregrad mit Annäherung an das Datum von informativ zu kritisch ansteigt.

Bei der Kapazitätsauslastung basiert der Schwellenwert für die Warnung bei Lastspitzen nun auf dem im Abonnement festgelegten Prozentsatz der zugesicherten Lastspitze anstatt auf einem festen Wert von 20 %. Wenn Ihre zugesicherte Lastspitze beispielsweise 40 % beträgt, wird die kritische Warnung bei 140 % der zugesicherten Kapazitätsauslastung ausgelöst.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html["Benachrichtigungsmonitore für Keystone Abonnements anzeigen und erstellen"].



[[15-june-2026]]
== 15. Juni 2026



[[console-setup-and-administration]]
=== Konsoleneinrichtung und -verwaltung



==== Veröffentlichung im privaten Modus (4.7.0)

Eine neue Version des privaten Modus steht jetzt zum Download aus dem https://mysupport.netapp.com/site/downloads["NetApp Support Site"^] bereit.

Die Version 4.7.0 enthält Aktualisierungen der folgenden NetApp Console-Komponenten und -Dienste.

[cols="3*"]
|===
| Komponente oder Service | In dieser Version enthalten | Änderungen seit der vorherigen privaten Modus-Version 


| Konsolenagent | 4.7.0 | Gehen Sie zu  https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2026-05-11.html["Was ist neu auf der NetApp Console-Seite"^] und informieren Sie sich über die Änderungen in Version 4.7.0. 


| NetApp Backup and Recovery | 5.4.0 (08. Juni 2026) | Gehe zu https://docs.netapp.com/us-en/data-services-backup-recovery/whats-new.html["Was ist neu auf der Seite NetApp Backup and Recovery"^]. 


| NetApp Data Classification | 1.54.0 (11. Mai 2026) | Gehe zu https://docs.netapp.com/us-en/data-services-data-classification/whats-new.html["Was ist neu auf der Seite NetApp Klassifizierung"^]. 
|===


[[backup-and-recovery]]
=== Sicherung und Wiederherstellung



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.06*: Diese Version enthält Trident Protect 26.06.
* *Anwendungserstellung bei Wiederherstellung überspringen*: Die automatische Erstellung benutzerdefinierter Anwendungsressourcenobjekte kann während Wiederherstellungsvorgängen nun übersprungen werden. Dies reduziert unnötige Einträge im Anwendungsinventar.
* *Wiederherstellung persistenter Volume Claims in VMs*: Bei der Wiederherstellung von VM-basierten Anwendungen ist es jetzt möglich, einzelne persistente Volume Claims wiederherzustellen, ohne die gesamte virtuelle Maschine wiederherstellen zu müssen, was die Wiederherstellung beschleunigt, wenn bestimmte Festplatten oder Volumes von Beschädigungen oder Datenverlust betroffen sind.
* *Verbesserungen im Jobmonitor*: Die Überwachung von Jobs bietet jetzt eine verbesserte Transparenz bei Kubernetes-Schutzjobs. Detaillierte Statusinformationen zu Jobs und Subjobs sowie der jeweils verwendete Zielspeicher sind einsehbar.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



[[11-june-2026]]
== 11. Juni 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Unterstützung für eine neue Azure-Region in Cloud Volumes ONTAP

Cloud Volumes ONTAP 9.12.1 GA und höher kann jetzt in Azure in der Region Malaysia West (malaysiawest) in einzelnen und mehreren Verfügbarkeitszonen bereitgestellt werden. Dies umfasst die Unterstützung sowohl für Einzelknoten- als auch für Hochverfügbarkeitsbereitstellungen (HA).

Eine Liste aller Regionen finden Sie unter https://bluexp.netapp.com/cloud-volumes-global-regions["Globale Regionskarte unter Azure"^].



[[08-june-2026]]
== 08. Juni 2026



[[console-setup-and-administration]]
=== Konsoleneinrichtung und -verwaltung



==== Console Agent 4.8.0

Die Version 4.8.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Console-Agenten enthält Sicherheitsverbesserungen und Fehlerbehebungen.



==== NetApp Console

Diese Version enthält die Sicherheitsverbesserungen und Fehlerbehebungen.



[[backup-and-recovery]]
=== Sicherung und Wiederherstellung



==== ONTAP Volumes Workloads-Verbesserungen

In dieser Version führt ONTAP Volumes-Workloads die folgende Verbesserung ein:

*Unterstützung für S3-kompatiblen Cloud-Speicher*: NetApp Backup and Recovery für Volumes-Workloads unterstützt jetzt das Sichern in S3-kompatiblen Cloud-Speicher.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



==== Hyper-V-Workload-Verbesserungen

In dieser Version werden für Hyper-V-Workloads die folgenden Verbesserungen eingeführt:

* *Wiederherstellen von Dateien und Ordnern in einer Gast-VM – Verbesserungen*: Sie können jetzt Dateien und Ordner aus einem Snapshot auf primärem oder sekundärem Speicher in einer Gast-Windows-VM wiederherstellen. Diese Funktion wird nun für CIFS- und SAN-VMs unterstützt.
* *Schutzgruppen verwenden jetzt die Zeitzone des Hyper-V-Hosts*: Schutzgruppen verwenden nun die Zeitzone des Hyper-V-Hosts. Schutzgruppen, die vor der Einführung der Host-Zeitzonenplanung erstellt wurden, verwenden weiterhin ihre zuvor konfigurierte Zeit (typischerweise UTC). Damit diese Schutzgruppen die Zeitzone des Hyper-V-Hosts verwenden, ist es erforderlich, die Zeitpläne neu zu erstellen. Weitere Informationen sind unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für Hyper-V Workloads"] verfügbar.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Übersicht zum Schutz von Hyper-V-Workloads"].



==== VMware-Workload-Verbesserungen

In dieser Version führt VMware Workloads die folgende Verbesserung ein:

* *Schutzgruppen verwenden jetzt die Zeitzonenplanung des Hosts*: Schutzgruppen verwenden nun die Zeitzone des VMware vCenter Servers. Schutzgruppen, die vor der Einführung der Host-Zeitzonenplanung erstellt wurden, laufen weiterhin in ihrer zuvor konfigurierten Zeitzone (typischerweise UTC). Um die vCenter-Zeitzone zu nutzen, ist es erforderlich, die Zeitpläne neu zu erstellen. Weitere Informationen sind unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für VMware Workloads"] verfügbar.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



[[data-classification]]
=== Datenklassifizierung



==== Allgemeine Verbesserungen

Diese Version der Datenklassifizierung beinhaltet Sicherheitsverbesserungen und Leistungsverbesserungen.



[[disaster-recovery]]
=== Notfallwiederherstellung



==== Kubernetes-Updates

Die Notfallwiederherstellung hat die folgenden Änderungen für Kubernetes-basierte Workloads eingeführt:



===== Testen Sie die Failover-Unterstützung für Kubernetes-Workloads

Die Notfallwiederherstellung unterstützt jetzt das Testen des Failover-Prozesses für Kubernetes-Workloads. Durch das Testen des Failovers können Sie Notfallwiederherstellungspläne validieren. Nach Abschluss des Tests können Sie den Test-Failover bereinigen, sodass das System die Testressourcen automatisch freigibt, um den Overhead zu reduzieren und die Konsistenz Ihrer Umgebung sicherzustellen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html#test-the-failover-process["Testen Sie den Failover-Prozess"^].



===== Geplante Test-Failover

Sie können jetzt Notfallwiederherstellungstests automatisieren, indem Sie Test-Failover planen. Sie können Zeitpläne für wiederkehrende Test-Failover festlegen, um Wiederherstellungspläne kontinuierlich ohne manuelle Eingriffe zu validieren, was dazu beiträgt, das Vertrauen in die Wiederherstellungsziele zu erhalten und Compliance-Anforderungen zu erfüllen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html#manage-replication-plans["Replikationspläne verwalten"^].



===== Geplante Erkennung von Kubernetes-Workloads

Mit der geplanten Erkennung können Sie steuern, wie häufig Disaster Recovery nach neuen Kubernetes-Workloads sucht. Sie können die Erkennungsintervalle an Ihren Betriebsrhythmus anpassen und so unnötigen Systemaufwand reduzieren, während gleichzeitig sichergestellt wird, dass neue Workloads rechtzeitig erkannt und geschützt werden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#edit-the-site-and-customize-the-discovery-schedule["Entdeckungszeitplan anpassen"^].



==== VMware-Updates



===== Schutz für leere Datenspeicher

Die Notfallwiederherstellung ermöglicht nun die Konfiguration des Schutzes für Datenspeicher, die keine virtuellen Maschinen (VMs) enthalten. Alle VMs, die dem Datenspeicher später hinzugefügt werden, werden von der Notfallwiederherstellung automatisch erkannt, zu diesem Zeitpunkt müssen Sie link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#add-subnet-mapping-for-a-vcenter-site["Mapping-Informationen"^] angeben.

Wenn Sie einen leeren Datenspeicher zu einem Schutzplan hinzufügen, müssen Sie entweder den Datenspeicher vor dem Failover aus dem Schutzplan entfernen oder ein erzwungenes Failover durchführen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Failover zu einem Remote-Standort"^].



===== Zuvor ausgeschlossene Datenspeicher in einen Schutzplan zurückholen

Datenspeicher, die zuvor vom Schutz ausgeschlossen waren, können nun wieder einbezogen werden. Diese Verbesserung bietet mehr Flexibilität bei der Verwaltung und Aktualisierung Ihrer Notfallwiederherstellungskonfigurationen im Laufe der Zeit.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Standorte, Ressourcengruppen und Replikationspläne verwalten"^].



===== Schnelleres Failover für VMFS-basierte Datastores

Die Notfallwiederherstellung hat die Failover-Performance für VMFS-basierte Datenspeicher verbessert. Host Bus Adapter (HBA) Rescan- und Datenspeicher-Mount-Operationen werden nun parallel ausgeführt, wodurch die gesamten Failover-Zeiten verkürzt und Ausfallzeiten während Wiederherstellungsereignissen minimiert werden.

Weitere Informationen zu Failover-Prozessen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Ausfallsicherung mit Notfallwiederherstellung"^].



[[ransomware-resilience]]
=== Ransomware-Resilienz



==== Verbesserte Flexibilität für Schutzstrategien

Die Ransomware-Resilienz bietet jetzt mehr Flexibilität bei der Auswahl von Ransomware-Erkennungsstrategien. Bisher mussten alle Ransomware-Schutzstrategien die Erkennung von Verschlüsselung umfassen. Jetzt können Sie eine Ransomware-Schutzstrategie aktivieren, die ausschließlich die Erkennung des Nutzerverhaltens verwendet.

Schutzstrategien können weiterhin sowohl die Erkennung von Verschlüsselung _als auch_ die Erkennung verdächtigen Nutzerverhaltens umfassen. Auch das Blockieren von Dateierweiterungen kann in jede Schutzstrategie integriert werden.

Wenn Sie einen Teil der Schutzstrategie einer bestehenden Richtlinie deaktivieren, können alle unter der vorherigen Version der Richtlinie erstellten Warnungen nur als "Behoben" und nicht als "Abgelehnt" markiert werden. Wenn Sie beispielsweise eine Schutzstrategie hatten, die die Erkennung von Verschlüsselung und verdächtigem Benutzerverhalten umfasste, Sie aber die Verschlüsselungserkennung deaktiviert haben, können Sie nur eine bestehende Verschlüsselungswarnung für diese Arbeitslast als behoben markieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Schützen Sie Ihre Workloads mit NetApp Ransomware Resilience Schutzstrategien"^].



==== SOAR-Playbook-Erweiterungen

Die SOAR-Playbooks für Ransomware-Resilienz bieten nun Maßnahmen zur Behebung von Problemen, nachdem Sie einen Benutzer gesperrt oder ein Volume offline genommen haben. Sie können ein Volume nun wieder online schalten und einen Benutzer entsperren, wenn die Aktion nicht als Ransomware-Bedrohung eingestuft wurde.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integrieren Sie ein SOAR-Playbook"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Unterstützung für neue EC2-Instanzen für Cloud Volumes ONTAP in AWS

Cloud Volumes ONTAP 9.16.1 und höher unterstützen die EC2-Instanzfamilien M6id und M6idn sowohl für neue als auch bestehende Einzelknoten- und Hochverfügbarkeits-Bereitstellungen (HA) in AWS. Diese Instanzen der 6. Generation bieten im Vergleich zu den Allzwecksystemen der 5. Generation eine höhere Rechenleistung, verbesserte Netzwerkfunktionen und eine insgesamt höhere Performance.

* *M6id-Instanzen*: Sie bieten ein ausgewogenes Verhältnis von Rechenleistung und Arbeitsspeicher mit schnellem, mit niedriger Latenz lokalem NVMe-Speicher. Alle M6id-Instanzgrößen unterstützen Flash Cache. Diese Instanzen eignen sich hervorragend für Workloads wie Protokollierung und Medienverarbeitung.
* *M6idn-Instanzen*: Bieten dieselben lokalen NVMe-Speicherfunktionen wie M6id-Instanzen. Alle M6idn-Instanzgrößen unterstützen Flash Cache.


Wir empfehlen die kleineren Instanztypen m6id.xlarge, m6id.2xlarge, m6idn.xlarge und m6idn.2xlarge nicht für Hochleistungs- oder speicherintensive Workloads. Für diese Workloads verwenden Sie einen Instanztyp mit einer höheren Kernanzahl und mehr Arbeitsspeicher.

Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Unterstützte Konfigurationen für Cloud Volumes ONTAP in AWS"^].



[[03-june-2026]]
== 3. Juni 2026



[[lifecycle-planning]]
=== Lebenszyklusplanung



==== Aktualisierungen der Funktionsnamen für die Lebenszyklusplanung

Die folgenden Funktionen der Lebenszyklusplanung haben Namensänderungen erfahren:

* Die Funktion „Tech refresh“ heißt jetzt *System Refresh*. Informationen dazu, wie  https://docs.netapp.com/us-en/console-lifecycle-planning/use/tech-refresh.html["eine Systemaktualisierung bewerten"].
* Die Funktion „Kapazitätserweiterungen“ heißt jetzt *Speichererweiterung*. Informationen dazu, wie  https://docs.netapp.com/us-en/console-lifecycle-planning/use/capacity-add.html["Speicherplatz erweitern"].
* Die Funktion „Verlängerungen“ heißt jetzt *Support Renewals*. Informationen dazu, wie  https://docs.netapp.com/us-en/console-lifecycle-planning/support/task-support-registration.html["Registrieren Sie sich für Support"].




[[digital-advisor]]
=== Digitaler Berater



==== Aktualisierungen des Namens des Digital Advisor-Widgets

Die folgenden Digital Advisor-Funktionen haben Namensänderungen:

* Die Funktion „Tech-Aktualisierung“ heißt jetzt „Systemaktualisierung“. Erfahren Sie, wie Sie link:https://docs.netapp.com/us-en/active-iq/evaluate-tech-refresh.html["eine Systemaktualisierung bewerten"].
* Die Funktion „Kapazitätserweiterungen“ heißt jetzt „Speichererweiterung“. Erfahren Sie mehr über link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Digital Advisor Widgets"].
* Die Funktion „Verlängerungen“ heißt jetzt „Support-Verlängerungen“. Erfahren Sie mehr über link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Digital Advisor Widgets"].




[[26-may-2026]]
== 26. Mai 2026



[[ransomware-resilience]]
=== Ransomware-Resilienz



==== Google Cloud NetApp Volumes-Unterstützung (Vorschau)

Ransomware Resilience unterstützt jetzt die Erstellung von Schutzgruppen für Workloads in Google Cloud NetApp Volumes-Systemen, sodass Sie mehrere Workloads unter einer Richtlinie organisieren können, um die Verwaltung zu vereinfachen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Erstellen Sie eine Schutzgruppe in Ransomware Resilience"^].



[[25-may-2026]]
== 25. Mai 2026



[[keystone]]
=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== Verbesserte Darstellung mehrerer Aktualisierungen am selben Tag in der Abonnement-Timeline

Die Abonnement-Zeitleiste zeigt nun eine Zahl an, wenn mehrere Abonnementaktualisierungen unterschiedlicher Art am selben Tag erfolgen, anstatt separater Symbole. Bewegen Sie den Mauszeiger über die Zahl, um alle Aktualisierungstypen dieses Tages anzuzeigen. Der heruntergeladene Bericht enthält für jede Aktualisierung eine separate Zeile und bietet Ihnen eine vollständige Übersicht aller Änderungen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/keystone-staas/integrations/subscription-timeline.html["Sehen Sie sich die Zeitleiste Ihrer Keystone Abonnements an"].



[[18-may-2026]]
== 18. Mai 2026



[[ransomware-resilience]]
=== Ransomware-Resilienz



==== Google Cloud NetApp Volumes-Unterstützung (Vorschau)

Ransomware Resilience unterstützt jetzt Google Cloud NetApp Volumes-Systeme und ermöglicht Ihnen so die effiziente Erkennung und Abwehr von Ransomware-Bedrohungen in Google Cloud NetApp Volumes. Bei der Erkennung zeigt Ransomware Resilience automatisch Workloads aus Google Cloud NetApp Volumes-Systemen an. Die erkannten Systeme werden im Ransomware Resilience-Dashboard angezeigt. Die Unterstützung für Google Cloud NetApp Volumes in Ransomware Resilience befindet sich derzeit in der Vorschauphase.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Erfahren Sie mehr über Ransomware Resilience"^]. Informationen zum Umfang der Google Cloud NetApp Volumes-Unterstützung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Einschränkungen der Ransomware-Resilienz"^].



==== Verbesserungen für Clean Restore

Die Funktion „Saubere Wiederherstellung“ unterstützt jetzt Berichte. Mithilfe von Berichten können Sie saubere Wiederherstellungen überprüfen und bewerten und diese Informationen offline als CSV-Datei speichern.

Die saubere Wiederherstellung unterstützt nun auch das Anhalten der Analyse. Wenn Sie die Analyse anhalten, müssen Sie die saubere Wiederherstellung erneut starten.

Weitere Informationen zu Berichten finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Berichte in Ransomware-Resilienz herunterladen"^]. Weitere Informationen zur Wiederherstellung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Stellen Sie Workloads mit einer sauberen Wiederherstellung wieder her"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Vereinfachte Cloud Volumes ONTAP-Bereitstellung in Azure

Mit Quick create können Sie Cloud Volumes ONTAP in Azure sowohl für Einzelknoten- als auch für Hochverfügbarkeitskonfigurationen (HA) bereitstellen. Dieser optimierte Prozess reduziert die Anzahl der Schritte im Vergleich zur fortschrittlichen Methoden, legt automatisch Standardwerte auf einer einzigen Seite fest und minimiert die Navigation, wodurch die Bereitstellung schneller und einfacher wird.

.Verwandte Links
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["Cloud Volumes ONTAP in Azure mit Schnellerstellung bereitstellen"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["Cloud Volumes ONTAP mit fortschrittlichen Methoden in Azure bereitstellen"^]




[[digital-advisor]]
=== Digitaler Berater



==== Wellness-Überprüfung

Ab Juli 2026 ist die Funktion „Wellness-Überprüfung“ im Digital Advisor nicht mehr verfügbar. Bei Fragen senden Sie bitte eine E-Mail an mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].



[[12-may-2026]]
== 12. Mai 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Flexible Abrechnung für Cloud Volumes ONTAP und Datendienste in AWS

NetApp bietet erweiterte Abrechnungsoptionen für Ihre Cloud Volumes ONTAP-Abonnements in AWS, sodass Sie mehr Kontrolle darüber haben, wie Sie für Cloud Volumes ONTAP-Kapazität und NetApp-Datendienste wie NetApp Backup and Recovery bezahlen. Bisher wurden alle Cloud Volumes ONTAP- und Datendienste-Nutzungen gemeinsam über die NetApp Intelligent Services (NIS)-Auflistung im AWS Marketplace abgerechnet.

Aufgrund von Änderungen im AWS Enterprise Discount Program (EDP) hat NetApp ein eigenständiges Cloud Volumes ONTAP-Abonnement im AWS Marketplace eingeführt, das es Ihnen ermöglicht, die Abrechnung der Cloud Volumes ONTAP-Kapazität von den Datendiensten zu trennen. Diese Trennung bietet Ihnen mehr Flexibilität bei der Verwaltung Ihrer EDP-Guthaben und -Kosten. NetApp empfiehlt die Nutzung des eigenständigen Abonnements für ein besseres Kostenmanagement Ihrer Cloud Volumes ONTAP Nutzung, während Sie das NIS-Abonnement weiterhin für die Abrechnung von Datendiensten nach dem 31. Juli 2026 verwenden sollten, wenn die EDP-Anforderungen in Kraft treten.

Das eigenständige Cloud Volumes ONTAP-Abonnement in AWS unterstützt ausschließlich gültige kapazitätsbasierte Essentials- oder Freemium-Lizenzpakete. Das Professional-Paket wird nicht unterstützt. Sie können die für Ihre Bedürfnisse optimale Abrechnungsmethode auswählen:

* *Eigenständiges Cloud Volumes ONTAP-Abonnement (Empfohlen)*: Bezahlen Sie Ihre Cloud Volumes ONTAP-Nutzung über das eigenständige Abonnement im AWS Marketplace, während die Datendienste weiterhin über das NIS-Abonnement abgerechnet werden. Dies ist die empfohlene Option für die meisten Kunden, die sowohl ein eigenständiges als auch ein NIS-Abonnement mit ihrem AWS-Konto in der NetApp Console verknüpft haben.
* *Kombiniertes NIS-Abonnement*: Bezahlen Sie sowohl Cloud Volumes ONTAP als auch Datendienste gemeinsam über den bestehenden NIS-Eintrag. Der kombinierte Ansatz gilt für Bestandskunden, die ausschließlich NIS-Abonnements mit ihrem AWS-Konto in der NetApp Console verknüpft haben. Allerdings empfiehlt NetApp, dass Sie Ihre Abrechnungspräferenz für Ihre Cloud Volumes ONTAP Nutzung festlegen und für eine bessere Kostenkontrolle auf das eigenständige Abonnement umsteigen.


Je nach Abonnementtyp ergeben sich folgende Szenarien:

.Nur Einzelabonnement (für Neukunden)
Wenn Sie in der NetApp Console nur ein eigenständiges AWS-Abonnement mit Ihrem AWS-Konto verknüpft haben und keine NIS-Abonnements besitzen, können Sie bei der Bereitstellung nur das Essentials-Lizenzpaket auswählen. Die Datenservices-Option *Backup und Recovery* steht Ihnen nicht zur Verfügung.

.Sowohl Einzelabonnements als auch NIS-Abonnements (für Bestandskunden)
Wenn Sie sowohl NIS- als auch eigenständige Abonnements mit Ihrem AWS-Konto verknüpft haben und keine Abrechnungspräferenz über die Registerkarte *Abrechnungseinstellungen* in der NetApp Console festgelegt haben, wird die Nutzung von Cloud Volumes ONTAP weiterhin standardmäßig über NIS abgerechnet. Dies ist auch die Standardeinstellung für jede Cloud Volumes ONTAP Instanz mit dem Professional-Paket, da das eigenständige Angebot Professional nicht unterstützt. Sie können eine Abrechnungspräferenz festlegen und auswählen, wie jeder Dienst abgerechnet wird:

* Legen Sie das Einzelabonnement als bevorzugtes Abrechnungskonto für Cloud Volumes ONTAP (mit Essentials-Paket) fest. Wenn Sie nur das Professional-Paket besitzen, können Sie es in ein Essentials-Paket umwandeln und Ihre Cloud Volumes ONTAP-Nutzung über die entsprechende Abrechnungseinstellung abrechnen. Wir empfehlen diese Vorgehensweise, da Sie so Ihre Cloud Volumes ONTAP EDP-Guthaben effizienter verwalten können.
* Nutzen Sie das NIS-Abonnement für die Abrechnung von Datendiensten oder die Nutzung von Cloud Volumes ONTAP über das Professional-Paket. Aktivieren Sie während der Bereitstellung den Datendienst *Backup und Recovery* und wählen Sie das Professional-Lizenzpaket aus, um Datendienste über das NIS-Abonnement abzurechnen.


.Nur NIS-Abonnement (Bestandskunden)
Dies gilt, wenn Sie bereits Kunde sind und NIS-Abonnements mit Ihrem AWS-Konto verknüpft haben. Sie können Cloud Volumes ONTAP und Datendienste weiterhin wie bisher gemeinsam abrechnen. Allerdings empfiehlt NetApp, für eine bessere Kostenkontrolle Ihrer Cloud Volumes ONTAP-Nutzung auf das eigenständige Abonnementmodell umzusteigen:

* Abonnieren Sie einen neuen eigenständigen Eintrag im AWS-Portal.
* Verknüpfen Sie das eigenständige Abonnement mit Ihrem AWS-Konto.
* Stellen Sie Ihre Abrechnungspräferenz auf das Einzelabonnement für die Nutzung von Cloud Volumes ONTAP mit dem Essentials-Paket ein.
* (Falls zutreffend) Wandeln Sie Ihr Professional-Paket in ein Essentials-Paket um und legen Sie die Abrechnungseinstellungen fest.
* Die Abrechnung von Datendiensten erfolgt weiterhin über Ihr NIS-Abonnement.



NOTE: Es kommt nicht zu doppelter Messung, wenn Sie mehrere Abonnementtypen verwenden oder zwischen Angeboten migrieren.

.Verwandter Link
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-set-up-licensing-aws.html["Lizenzierung für Cloud Volumes ONTAP in AWS einrichten"^]
* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-capacity-licenses.html#change-charging-methods["Ändern Sie die Abrechnungsmethoden für Kapazitätslizenzen"^]




[[11-may-2026]]
== 11. Mai 2026



[[console-setup-and-administration]]
=== Konsoleneinrichtung und -verwaltung



==== Console Agent 4.7.0

Die Version 4.7.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Console-Agenten enthält Sicherheitsverbesserungen und Fehlerbehebungen.



==== NetApp Console

Diese Version enthält die folgende neue Funktion.

.Überprüfen Sie Ihre Console-Organisation
Standardmäßig zeigt Digital Advisor alle NetApp Konten an, die mit Ihrem Unternehmen verknüpft sind, und nicht nur Ihre Console-Organisation. Um die Anzeige in Digital Advisor auf ein bestimmtes Konto zu beschränken, verifizieren Sie das Geschäftskonto, das Sie mit Ihrer Console-Organisation verwenden möchten. link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-organization-verify.html["Erfahren Sie, wie Sie Ihre Console-Organisation überprüfen können."^]



[[backup-and-recovery]]
=== Sicherung und Wiederherstellung



==== Hyper-V-Workload-Verbesserungen

In dieser Version werden für Hyper-V-Workloads die folgenden Verbesserungen eingeführt:

* *VMs auf SAN-Speicher schützen*: Sie können jetzt VMs auf SAN-Objektspeicher schützen.
* *Verbesserungen bei der Wiederherstellung an alternativen Speicherorten*: Sie können jetzt von primären und sekundären Speicherorten für VMs auf SAN-Speicher an einem alternativen Speicherort wiederherstellen.
* *Dateien und Ordner in einer Gast-VM*: Sie können jetzt Dateien und Ordner aus einem Snapshot auf dem primären Speicher in einer Gast-Windows-VM wiederherstellen. Diese Funktion wird nur für CIFS-VMs unterstützt.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Übersicht zum Schutz von Hyper-V-Workloads"].



==== Verbesserungen für KVM-Workloads

In dieser Version wird für KVM-Workloads die folgende Verbesserung eingeführt:

*Wiederherstellung an alternativem Speicherort*: Sie können KVM-VMs jetzt an einem alternativen Zielort wiederherstellen (diese Funktion ist jetzt allgemein verfügbar).

Weitere Informationen zum Schutz von KVM-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Übersicht über den Schutz von KVM-Workloads"] .



==== Verbesserungen der Oracle Database Workloads

In dieser Version werden die folgenden Verbesserungen für Oracle Database workloads eingeführt:

* *Unterstützung für Oracle AI Database 26ai*: Backup und Recovery unterstützen jetzt Oracle AI Database 26ai.
* *Unterstützung für die Backup-Verifizierung*: Sie können jetzt Backup-Richtlinien konfigurieren, um die Integrität Ihrer Oracle Datenbank-Backups automatisch zu überprüfen.


Weitere Informationen zum Schutz von Oracle Database-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Übersicht zum Schutz von Oracle Database-Workloads"].



==== VMware-Workload-Verbesserungen

In dieser Version führt VMware workloads die folgenden Verbesserungen ein:

* *Unterstützung für datenspeicherübergreifende Schutzgruppen*: Sie können nun das Verhalten von Schutzgruppen beim Schutz virtueller Maschinen auswählen, deren virtuelle Festplatten sich über mehrere Datenspeicher erstrecken.
* *Klonunterstützung*: Sie können jetzt Klone von Snapshots virtueller Maschinen aus dem primären und sekundären Speicher erstellen.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.05.1*: Diese Version enthält Trident Protect 26.05.1.
* *Wiederherstellung direkt am Ort für VM-basierte Anwendungen*: Sie können VM-basierte Anwendungen jetzt im ursprünglichen Namespace und ursprünglichen Cluster wiederherstellen.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



[[data-classification]]
=== Datenklassifizierung



==== Verbesserte Konfigurationsseite

Die Datenklassifizierung hat die Konfigurationsseite aktualisiert und verbessert, wodurch die Verwaltung von Einstellungen, Systemen, das Aktivieren von Scans und die Überwachung des Systemzustands benutzerfreundlicher gestaltet werden können. Die neue Konfigurationsseite bietet die bestehenden Funktionen in einem übersichtlicheren Format und ermöglicht zusätzlich das Filtern von Systemen nach Typ, Fehlerstatus und Scanstatus. Die neue Seite bietet außerdem eine Zusammenfassung der verbundenen Systeme sowie Übersichten über aktive und konfigurierte Scans.

Überprüfen Sie eine link:https://youtu.be/_8YJ3KyZ7nI["Video-Anleitung"^]. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Scannen Sie Datenquellen mit Data Classification"^].



==== Compliance-Administrator-IAM-Rolle

Data Classification unterstützt jetzt eine Compliance-Administratorrolle zur Verwaltung von Berechtigungen in Data Classification. Die Compliance-Administratorrolle hat keinen Zugriff auf Ressourcen, einschließlich Konsolenagenten und Arbeitsbereichen. Benutzer mit der Compliance-Administratorrolle müssen mindestens einer weiteren Rolle zugeordnet sein.

Bei der Installation der Data Classification sollten Sie entweder die Rolle eines Console Platform Admin oder die Compliance Admin Rolle haben.

Wenn Sie bereits ein Benutzer sind, sollte der Zugriff wie gewohnt weiterlaufen. Beispielsweise hat eine Plattformrolle mit einer Ordner- oder Projektadministratorrolle bereits bestehenden Zugriff.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Datenklassifizierungsrollen"^].



==== Datenklassifizierung mit OVA implementieren

NetApp Data Classification unterstützt jetzt die Bereitstellung mit VMware Open Virtual Appliance (OVA) und bietet eine vereinfachte Bereitstellungsstrategie für lokale VMware vSphere-Umgebungen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Datenklassifizierung mit OVA implementieren"^].



[[disaster-recovery]]
=== Notfallwiederherstellung



==== Unterstützung für Kubernetes-basierte Workloads (Vorschau)

NetApp Disaster Recovery unterstützt jetzt auch Kubernetes-basierte Workloads. Mit Kubernetes-Unterstützung können Sie Anwendungen schützen, die auf Kubernetes-Clustern laufen, einschließlich OpenShift Virtualisierungsumgebungen. Disaster Recovery unterstützt link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["jede derzeit von Trident Protect unterstützte Kubernetes-Version"^], was eine nahtlose Integration und robuste Disaster-Recovery-Funktionen für containerisierte Anwendungen gewährleistet.

Hauptmerkmale der Kubernetes-basierten Workload-Unterstützung:

* **Umfassende Kompatibilität**: Disaster Recovery unterstützt alle mit Trident Protect kompatiblen Kubernetes-Versionen, einschließlich Red Hat OpenShift Virtualization.
* **Anwendungszentrierter Schutz**: Sie können Kubernetes-Workloads jetzt auf Anwendungsebene schützen und so die Wiederherstellung kritischer Dienste bei Failover-Ereignissen sicherstellen.
* **Vereinfachte Orchestrierung**: Disaster Recovery bietet intuitive Workflows zur Automatisierung der Sicherung und Replikation von Kubernetes-Workloads und nutzt dabei dieselbe effiziente SnapMirror-Technologie wie in VMware-Umgebungen.


Die Unterstützung für Kubernetes-basierte Workloads befindet sich derzeit in der Vorschauphase. Um mit dem Schutz von Kubernetes-basierten Workloads zu beginnen, siehe link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html["Kubernetes-Anforderungen für NetApp Disaster Recovery"^].



[[ransomware-resilience]]
=== Ransomware-Resilienz



==== Verbesserungen für Clean Restore

Die Funktion „Saubere Wiederherstellung“ unterstützt jetzt die Wiederherstellung an einem alternativen Speicherort, sodass Sie Volumes auf verschiedenen Systemen, Speicher-VMs und Aggregaten wiederherstellen können, die vom selben Console-Agenten verwaltet werden. Außerdem wurde die Sieben-Tage-Beschränkung für die Suche nach geeigneten Snapshots für die Wiederherstellung aufgehoben. Die Funktion „Saubere Wiederherstellung“ durchsucht nun weiterhin alle verfügbaren Snapshots nach einem geeigneten Wiederherstellungspunkt, unabhängig vom Abstand zum Ransomware-Ereignis.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Stellen Sie Workloads mit einer sauberen Wiederherstellung wieder her"^].



==== Google SecOps SIEM-Unterstützung

Ransomware Resilience unterstützt jetzt Security Information and Event Management (SIEM) mit Google SecOps, wodurch Sie Daten automatisch an Google SecOps senden können, um die Bedrohungsanalyse und -erkennung zu optimieren.

Informationen zur Konfiguration finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Verbinden Sie NetApp Ransomware Resilience mit einem SIEM"^].



==== Azure NetApp Files-Unterstützung ist jetzt allgemein verfügbar

Ransomware Resilience unterstützt jetzt Azure NetApp Files-Systeme und ermöglicht Ihnen so die effiziente Erkennung und Abwehr von Ransomware-Bedrohungen in Azure NetApp Files. Bei der Erkennung von Workloads zeigt Ransomware Resilience nun Azure NetApp Files im Schutz-Dashboard an. Die Unterstützung von Ransomware Resilience für Azure NetApp Files umfasst Erkennungs- und Schutzstrategien, die ausschließlich auf Snapshots basieren. Die Unterstützung für Azure NetApp Files ist ab sofort allgemein verfügbar (GA).

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Erfahren Sie mehr über Ransomware Resilience"^].



==== SOAR-Unterstützung für das Blockieren von Benutzern

Ransomware Resilience unterstützt jetzt das Blockieren einzelner Nutzer mit Google SecOps und Splunk SOAR Playbooks. Mit dieser Erweiterung können Sie das Blockieren von Nutzern automatisieren, wenn Ransomware Resilience verdächtige Nutzeraktivitäten wie einen Datenverstoß oder massenhafte Datenlöschungen erkennt.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integrieren Sie ein SOAR-Playbook"^].



[[05-may-2026]]
== 05. Mai 2026



[[backup-and-recovery]]
=== Sicherung und Wiederherstellung



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.05*: Diese Version enthält Trident Protect 26.05.
* *Upgrade Trident Protect von Backup und Recovery*: Wenn auf Ihrem Kubernetes-Cluster Trident Protect 26.05 oder neuer ausgeführt wird, können Sie Trident Protect jetzt direkt von Backup und Recovery aus aktualisieren.
* *Native Unterstützung für den Schutz von VMs*: Sie können jetzt VM-basierte Anwendungen erstellen, mit denen Sie virtuelle Maschinen genauso schützen können wie jede andere Anwendung.
* *Ressourcentransformationen*: Sie können jetzt Ressourcentransformationen und Ressourcentransformationsvorlagen verwenden, um während des Wiederherstellungsprozesses Ressourcenattribute hinzuzufügen, zu entfernen und zu ändern.
* *Geschützte Ressourcen anzeigen*: Sie können nun die in jedem Wiederherstellungspunkt einer Anwendung enthaltenen Ressourcen anzeigen und einen detaillierten JSON-Bericht herunterladen. Dies gibt Ihnen vollständige Transparenz über Ihre Wiederherstellungspunkte und vereinfacht die Audit-Compliance.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



[[27-april-2026]]
== 27. April 2026



[[keystone]]
=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== Umbenanntes Label für bereitgestellte Kapazität

Die Bezeichnung *Bereitgestellte Kapazität* wurde in *Bereitgestellte Volumenkapazität* umbenannt. Die aktualisierte Bezeichnung wird auch in den zugehörigen CSV- und Excel-Berichten berücksichtigt.



==== Prognoseumschalter für aufgelaufene Burst-Nutzung

Sie können jetzt die *Prognose*-Funktion in der Ansicht *Aufgelaufener Burst* auf der Registerkarte *Verbrauchstrend* nutzen, um den aufgelaufenen Burst-Verbrauch für die nächsten 120 Tage ab dem aktuellen Datum zu prognostizieren. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/keystone-staas/integrations/consumption-tab.html#view-forecast-data["Prognosedaten anzeigen"].



[[20-april-2026]]
== 20. April 2026



[[backup-and-recovery]]
=== Sicherung und Wiederherstellung



==== VMware-Workload-Verbesserungen

In dieser Version führt VMware Workloads die folgende Verbesserung ein:

*ASA r2 SAN-Unterstützung*: VMware-Workloads unterstützen jetzt den Schutz von VMs auf VMFS-Datenspeichern, die in NetApp ASA r2 SAN-only-Umgebungen gehostet werden.

Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].
