---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind. 
---
= Aktuelle Änderungen in der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind.  Eine vollständige Versionshistorie finden Sie unterlink:release-notes-index.html["Vollständiger Satz der Versionshinweise"] für jeden einzelnen Dienst.



== Verwaltungsfunktionen

In diesem Abschnitt werden neue Funktionen im Zusammenhang mit den Verwaltungsfunktionen der NetApp Console beschrieben: Organisationen, Identifizierung und Zugriff, Konsolenagenten, Anmeldeinformationen des Cloud-Anbieters und mehr.



== Warnungen



== Amazon FSx für ONTAP



== Amazon S3-Speicher



== Azure Blob-Speicher



== Azure NetApp Files



== Sicherung und Wiederherstellung



== Datenklassifizierung



== Cloud Volumes ONTAP



== Kopieren und Synchronisieren



== Digitaler Berater



== Licenses and subscriptions



=== 06. Oktober 2025



==== BlueXP heißt jetzt NetApp Console

Die NetApp Console basiert auf der verbesserten und neu strukturierten BlueXP -Grundlage und ermöglicht die zentrale Verwaltung von NetApp -Speicher und NetApp Data Services in On-Premises- und Cloud-Umgebungen auf Unternehmensniveau. Sie liefert Einblicke in Echtzeit, schnellere Arbeitsabläufe und eine vereinfachte Verwaltung mit hoher Sicherheit und Konformität.

Einzelheiten zu den Änderungen finden Sie imlink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Versionshinweise zur NetApp Console"] .



=== 10. März 2025



==== Möglichkeit zum Entfernen von Abonnements

Sie können jetzt Abonnements aus der digitalen Geldbörse entfernen, wenn Sie diese abbestellt haben.



==== Anzeigen der verbrauchten Kapazität für Marketplace-Abonnements

Beim Anzeigen von PAYGO-Abonnements können Sie jetzt die verbrauchte Kapazität des Abonnements anzeigen.



=== 10. Februar 2025

Die BlueXP digital wallet wurde für eine einfachere Nutzung neu gestaltet und bietet jetzt zusätzliche Funktionen zur Abonnement- und Lizenzverwaltung.



==== Neues Übersichts-Dashboard

Auf der Homepage der digitalen Geldbörse finden Sie ein aktualisiertes Dashboard Ihrer NetApp -Lizenzen und Marketplace-Abonnements mit der Möglichkeit, detaillierte Informationen zu bestimmten Diensten, Lizenztypen und erforderlichen Aktionen anzuzeigen.



==== Konfigurieren von Abonnements für Anmeldeinformationen

Mit der BlueXP digital wallet können Sie jetzt Ihre Abonnements für Anbieteranmeldeinformationen konfigurieren. Normalerweise tun Sie dies, wenn Sie zum ersten Mal ein Marketplace-Abonnement oder einen Jahresvertrag abschließen. Bisher konnten die Anmeldeinformationen des Abonnements nur auf der Seite „Anmeldeinformationen“ geändert werden.



==== Zuordnen von Abonnements zu Organisationen

Sie können jetzt die Organisation, mit der ein Abonnement verknüpft ist, direkt aus der digitalen Geldbörse aktualisieren.



==== Verwalten von Cloud Volume ONTAP Lizenzen

Sie verwalten Cloud Volumes ONTAP -Lizenzen jetzt über die Startseite oder die Registerkarte *Direktlizenzen*. Verwenden Sie die Registerkarte *Marketplace-Abonnements*, um Ihre Abonnementinformationen anzuzeigen.



=== 5. März 2024



==== BlueXP disaster recovery

Mit der BlueXP digital wallet können Sie jetzt Lizenzen für die BlueXP disaster recovery verwalten. Sie können Lizenzen hinzufügen, Lizenzen aktualisieren und Details zur lizenzierten Kapazität anzeigen.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Erfahren Sie, wie Sie Lizenzen für BlueXP -Datendienste verwalten"]



=== 30. Juli 2023



==== Verbesserungen bei Nutzungsberichten

Es sind jetzt mehrere Verbesserungen für die Cloud Volumes ONTAP -Nutzungsberichte verfügbar:

* Die Einheit TiB ist jetzt im Namen der Spalten enthalten.
* Ein neues _Knoten(e)_-Feld für Seriennummern ist jetzt enthalten.
* Im Bericht zur Nutzung von Storage-VMs ist jetzt eine neue Spalte „Workload-Typ“ enthalten.
* Die Namen der Arbeitsumgebungen sind jetzt in den Berichten zur Speicher-VM- und Volume-Nutzung enthalten.
* Der Datenträgertyp _Datei_ trägt jetzt die Bezeichnung _Primär (Lesen/Schreiben)_.
* Der Volumetyp _sekundär_ trägt jetzt die Bezeichnung _Sekundär (DP)_.


Weitere Informationen zu den Nutzungsberichten finden Sie unter https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Nutzungsberichte herunterladen"] .



== Notfallwiederherstellung



== Systeme der E-Serie



== Lebenszyklusplanung



== Edge-Caching

Der Edge-Caching-Dienst wurde am 7. August 2024 entfernt.



== Google Cloud NetApp Volumes



== Google Cloud-Speicher



== Keystone



== Kubernetes

Die Unterstützung für die Erkennung und Verwaltung von Kubernetes-Clustern wurde am 7. August 2024 entfernt.



== Migrationsberichte

Der Dienst für Migrationsberichte wurde am 7. August 2024 entfernt.



== On-Premise- ONTAP Cluster



== Betriebsstabilität

Die Funktionen zur betrieblichen Ausfallsicherheit wurden am 22. August 2025 entfernt.



== Ransomware-Resilienz



== Sanierung

Der Sanierungsdienst wurde am 22. April 2024 entfernt.



== Replikation



== Software-Updates



== StorageGRID



== Cloud-Tiering



=== 06. Oktober 2025



==== BlueXP tiering heißt jetzt NetApp Cloud Tiering

BlueXP tiering wurde in NetApp Cloud Tiering umbenannt.



==== BlueXP heißt jetzt NetApp Console

Die NetApp Console basiert auf der verbesserten und neu strukturierten BlueXP -Grundlage und ermöglicht die zentrale Verwaltung von NetApp -Speicher und NetApp Data Services in On-Premises- und Cloud-Umgebungen auf Unternehmensniveau. Sie liefert Einblicke in Echtzeit, schnellere Arbeitsabläufe und eine vereinfachte Verwaltung mit hoher Sicherheit und Konformität.

Einzelheiten zu den Änderungen finden Sie imlink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Versionshinweise zur NetApp Console"] .



=== 09. August 2023



==== Verwenden Sie ein benutzerdefiniertes Präfix für den Bucket-Namen

In der Vergangenheit mussten Sie beim Definieren des Bucket-Namens das Standardpräfix „fabric-pool“ verwenden, z. B. _fabric-pool-bucket1_.  Jetzt können Sie beim Benennen Ihres Buckets ein benutzerdefiniertes Präfix verwenden.  Diese Funktion ist nur beim Tiering von Daten auf Amazon S3 verfügbar. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Mehr erfahren"] .



==== Suche nach einem Cluster über alle BlueXP Connectors

Wenn Sie mehrere Connectors verwenden, um alle Speichersysteme in Ihrer Umgebung zu verwalten, befinden sich einige Cluster, auf denen Sie Tiering implementieren möchten, möglicherweise in unterschiedlichen Connectors.  Wenn Sie nicht sicher sind, welcher Connector einen bestimmten Cluster verwaltet, können Sie mithilfe von Cloud Tiering über alle Connectors hinweg suchen. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Mehr erfahren"] .



=== 04. Juli 2023



==== Passen Sie die Bandbreite an, um inaktive Daten zu übertragen

Wenn Sie Cloud Tiering aktivieren, kann ONTAP eine unbegrenzte Netzwerkbandbreite nutzen, um die inaktiven Daten von Volumes im Cluster in den Objektspeicher zu übertragen.  Wenn Sie feststellen, dass sich die Datenverkehrsstaffelung auf die normale Arbeitslast der Benutzer auswirkt, können Sie die Bandbreite drosseln, die während der Übertragung genutzt werden kann. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Mehr erfahren"] .



==== Im Benachrichtigungscenter angezeigtes Tiering-Ereignis

Das Tiering-Ereignis „Tieren Sie zusätzliche Daten vom Cluster <Name> in den Objektspeicher, um Ihre Speichereffizienz zu erhöhen“ wird jetzt als Benachrichtigung angezeigt, wenn ein Cluster weniger als 20 % seiner kalten Daten tieret – einschließlich Clustern, die keine Daten tieren.

Diese Benachrichtigung ist eine „Empfehlung“, die Ihnen dabei helfen soll, Ihre Systeme effizienter zu gestalten und Speicherkosten zu sparen. Es bietet einen Link zum https://www.netapp.com/data-services/tiering/tco-calculator/["Rechner für die Gesamtbetriebskosten und Einsparungen bei Cloud Tiering"^] um Ihnen bei der Berechnung Ihrer Kosteneinsparungen zu helfen.



== Volume-Caching



== Workload-Factory



=== 06. Oktober 2025



==== BlueXP workload factory jetzt NetApp Workload Factory

BlueXP wurde umbenannt und neu gestaltet, um seine Rolle bei der Verwaltung Ihrer Dateninfrastruktur besser widerzuspiegeln.  Aus diesem Grund wurde die BlueXP workload factory in NetApp Workload Factory umbenannt.



==== Ask Me-Integration mit MCP

Ask Me, der KI-Assistent von Workload Factory, ist in das Model Context Protocol (MCP) integriert.  Mithilfe von MCP stellt Ask Me eine sichere Schnittstelle zu externen Umgebungen und Abfrage-API-Tools her, um Antworten zu liefern, die auf Ihre spezifische Speicherumgebung zugeschnitten sind.



=== 05. Oktober 2025



==== Neue Benachrichtigung für Speicher

Der Benachrichtigungsdienst von NetApp Workload Factory umfasst die Benachrichtigung bei gut strukturierten Problemen für Storage.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Benachrichtigungen für NetApp Workload Factory"]



=== 09. September 2025



==== Neue Benachrichtigung für Speicher

Der Benachrichtigungsdienst der BlueXP workload factory umfasst die Benachrichtigung für die automatische Kapazitätsverwaltung für Speicher.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Benachrichtigungen für die BlueXP workload factory"]
