---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind. 
---
= Aktuelle Änderungen in der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Änderungen an den Funktionen und Datendiensten, die Teil der NetApp Console sind.  Eine vollständige Versionshistorie finden Sie unterlink:release-notes-index.html["Vollständiger Satz der Versionshinweise"] für jeden einzelnen Dienst.



== Veraltete Dienste



=== Edge-Caching

Der Edge-Caching-Dienst wurde am 7. August 2024 entfernt.



=== Kubernetes

Die Unterstützung für die Erkennung und Verwaltung von Kubernetes-Clustern wurde am 7. August 2024 entfernt.



=== Migrationsberichte

Der Dienst für Migrationsberichte wurde am 7. August 2024 entfernt.



=== Betriebsstabilität

Die Funktionen zur betrieblichen Ausfallsicherheit wurden am 22. August 2025 entfernt.



=== Sanierung

Der Sanierungsdienst wurde am 22. April 2024 entfernt.



== 09. Februar 2026



=== Konsoleneinrichtung und -verwaltung



==== Console Agent 4.4.0

Die Version 4.4.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Console-Agenten enthält Sicherheitsverbesserungen und Fehlerbehebungen.



==== NetApp Console

Diese Version enthält Folgendes:

.Unterstützung für rollenbasierte Zugriffssteuerung für NetApp Backup and Recovery-Workloads (Oracle und Microsoft SQL Server)
Sie können Backup- und Wiederherstellungs-Workloads (Oracle und Microsoft SQL Server) Projekten zuordnen. Nach der Zuordnung zu einem Projekt können Benutzer, die für das Projekt eine Backup- und Wiederherstellungsrolle zugewiesen bekommen haben, mit den Workloads arbeiten. Andere Workloads werden derzeit nicht mit rollenbasiertem Zugriff unterstützt.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-rbac-setup.html["Erfahren Sie mehr über die Einrichtung von rollenbasiertem Zugriff für Backup- und Recovery-Workloads."^]



=== Sicherung und Wiederherstellung



==== Microsoft Hyper-V-Workloads, die in General Availability (GA) unterstützt werden

Die Unterstützung für Microsoft Hyper-V-Workloads ist jetzt allgemein verfügbar (GA) in NetApp Backup and Recovery.



==== KVM-Workloads, die in der General Availability (GA) unterstützt werden

Die Unterstützung für KVM-Workloads ist jetzt allgemein verfügbar (GA) in NetApp Backup and Recovery.



==== Kubernetes-Workloads-Erweiterungen

Diese Version von Kubernetes-Workloads bietet die folgenden erweiterten Funktionen:

* *CR-Workflow-Unterstützung*: Sie können jetzt gängige Schutzaufgaben sowohl mit CRs als auch über die Backup and Recovery-Weboberfläche durchführen.
* *Clustermigration*: Sie können jetzt bestehende Kubernetes-Cluster, die mit Trident Protect geschützt sind, zu Backup and Recovery hinzufügen.
* *Unterstützung des Alerting-Frameworks*: Sie können jetzt E-Mail- und UI-Benachrichtigungen für bestimmte Kubernetes-Workload-Ereignisse erhalten.
* *Integration der Registerkarte "Wiederherstellen"*: Sie können jetzt über das Menü "Wiederherstellen" auf die Aktionen zur Wiederherstellung von Kubernetes-Workloads zugreifen.
* *Unterstützung für die 3-2-1-Fanout-Backup-Architektur*: Sie können jetzt eine 3-2-1-Fanout-Architektur in Ihrer Datensicherungsstrategie verwenden, wenn Sie Kubernetes-Workloads schützen.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



==== Verbesserungen der Oracle Database Workloads

Diese Version der Oracle Database Workloads bietet die folgenden erweiterten Funktionen:

* *Unterstützung für Nicht-Root-Benutzer*: Nicht-Root-Benutzer können nun Sicherungs-, Wiederherstellungs- und Klonvorgänge durchführen, was die Sicherheit und Compliance verbessert.
* *Klonunterstützung*: Klonfunktionen werden jetzt in primären und sekundären NAS-, SAN- und ASM-Umgebungen mithilfe der ASM library v2 unterstützt, wodurch koordinierte Schutz-Workflows ermöglicht werden.
* *Unterstützung für das Aufteilen von Klonen*: Sie können jetzt beschreibbare Snapshots (Klone) von ihren übergeordneten Volumes trennen, Speicherplatz freigeben und unabhängige Operationen ermöglichen.
* *Sicherung und Wiederherstellung für Objektspeicher*: Native Sicherungs- und Wiederherstellungsfunktionen werden jetzt für objektbasierte S3-kompatible Speicherziele unterstützt.
* *Clone Lifecycle Management (CLM)*: Klonaktualisierungsvorgänge werden auf dem primären Speicher unterstützt.
* *Auf alternativen Host klonen*: Sie können jetzt Datenbanken zu Test- oder Analysezwecken sowohl vom primären als auch vom sekundären Speicher auf einen anderen Host klonen.
* *ONTAP Konsistenzgruppen-Support*: ONTAP Konsistenzgruppen werden jetzt unterstützt, wodurch applikationskonsistente Snapshots über mehrere Volumes hinweg gewährleistet werden.
* Backup and Recovery unterstützt jetzt die folgenden Datensicherungsstrategie-Architekturen für Oracle Database-Workloads:
+
** 3-2-1 Fanout
** Festplatte zu Festplatte
** Festplatte zu Objektspeicher
** Kaskadierend
** Lokaler Snapshot




Weitere Informationen zum Schutz von Oracle Database-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Übersicht zum Schutz von Oracle Database-Workloads"].



=== Datenklassifizierung



==== Version 1.50

Diese Version der Datenklassifizierung enthält Fehlerbehebungen und die folgenden Aktualisierungen:

.Aktivieren Sie die Datenklassifizierung mit Amazon FSxN für ONTAP direkt aus der NetApp Console-Übersicht
Sie können Amazon FSxN für ONTAP-Systeme jetzt direkt von der NetApp Console-Oberfläche aus aktivieren, sodass Sie die Datenklassifizierung für Ihre FSxN-Systeme schneller starten können.

Weitere Informationen zur Verwendung von Data Classification mit Amazon FSxN für ONTAP finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-fsx.html["Amazon FSxN nach ONTAP-Volumes scannen"^].

.Erhöhtes Exportlimit für die Untersuchung von Verzeichnissen
Beim Export eines Untersuchungsberichts zu Verzeichnissen aus dem Untersuchungs-Dashboard können Sie nun 10.000 Zeilen einbeziehen. Diese Erhöhung gegenüber dem vorherigen Limit von 5.000 Zeilen unterstützt umfangreichere Untersuchungen im Bereich Daten-Governance und Compliance.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Daten untersuchen"^].

.Erhöhtes Limit für Kopieren und Verschieben
Beim Kopieren oder Verschieben von Dateien können Sie jetzt Dateien mit einer Größe von bis zu 250 MB kopieren oder verschieben, eine Erhöhung gegenüber dem vorherigen Limit von 50 MB.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Daten untersuchen"^].

.Verbesserte Darstellung für Bildschirme mit niedriger Auflösung
Data Classification hat die Anzeigeleistung für Bildschirme mit niedriger Auflösung verbessert und so die Benutzererfahrung verbessert.



=== Cloud Volumes ONTAP



==== Unterstützung für Google Cloud Infrastructure Manager

Cloud Volumes ONTAP 9.16.1 und höher unterstützen jetzt  https://docs.cloud.google.com/infrastructure-manager/docs/overview["Google Cloud Infrastructure Manager"^] (IM) anstelle von  https://docs.cloud.google.com/deployment-manager/docs/deprecations["Cloud-Bereitstellungsmanager"^] (DM) für neue Bereitstellungen in Google Cloud. Google wird Deployment Manager als Infrastrukturdienst in naher Zukunft zugunsten des fortschrittlicheren Infrastructure Manager einstellen.

Stellen Sie Cloud Volumes ONTAP automatisch für die Nutzung des Infrastructure Manager bereit oder wechseln Sie Ihre bestehenden Bereitstellungen im Deployment Manager mithilfe eines Konvertierungstools zum Infrastructure Manager. Die Konvertierung ist ein einmaliger Vorgang, nach dem Ihre Systeme automatisch den Infrastructure Manager verwenden. Siehe  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-gcp-dm-im-conv.html["Vorhandene Cloud Volumes ONTAP-Bereitstellungen für Google Cloud Infrastructure Manager konfigurieren"^] für Anweisungen zur Ausführung des Übergangstools.

Cloud Volumes ONTAP-Systeme, die Infrastructure Manager verwenden, nutzen Google Cloud Storage-Buckets, um Daten und Datensätze in der Zone der ersten Bereitstellung zu speichern, um Bereitstellungsdatensätze zu speichern, die für nachfolgende Bereitstellungen wiederverwendet werden. Für diese Buckets können zusätzliche Kosten anfallen, aber bearbeiten oder löschen Sie die Buckets oder deren Inhalt nicht:

* `gs://netapp-cvo-infrastructure-manager-<project id>/dm-to-im-convert`: zum Speichern von Cloud Volumes ONTAP Terraform-Dateien
* `<gcp project number>-<region>-blueprint-config`: zum Speichern von Google Cloud Terraform-Artikeln


.Verwandte Links
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-getting-started-gcp.html["Erste Schritte mit Cloud Volumes ONTAP in Google Cloud"^]
* https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#console-agent-4-2-0["NetApp Console Agent 4.2.0 Versionshinweise"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Erforderliche Berechtigungen für Google Cloud Infrastructure Manager"^]




== 04. Februar 2026



=== Digitaler Berater



==== Neuer Sicherheitsbericht für umfassende Sicherheitsaufsicht

Digital Advisor enthält jetzt einen Sicherheitsbericht, der eine einheitliche Ansicht der ONTAP-Sicherheitsrisiken in Ihrer Speicherumgebung bietet. Dieser Bericht ermöglicht eine schnellere Erkennung von Fehlkonfigurationen, Compliance-Lücken und Sicherheitsproblemen in Clustern, SVMs und Volumes und hilft Ihnen, eine sichere Speicherinfrastruktur aufrechtzuerhalten.



==== Erweiterte Upgrade Advisor-Unterstützung für gemischte Patch-Versionen

Upgrade Advisor generiert jetzt Upgrade-Berichte für Cluster, in denen Knoten unterschiedliche Patch-Level innerhalb derselben ONTAP Hauptversion verwenden. Diese Verbesserung gewährleistet, dass Kunden Upgrades nahtlos durchführen können, solange der Cluster nicht verschiedene Hauptversionen umfasst, und bietet so mehr Flexibilität bei der Upgrade-Planung.



==== Erweiterte Unterstützung für ONTAP-Versionen mit abgelaufenem begrenztem Support

Upgrade Advisor unterstützt jetzt die Erstellung von Upgrade-Plänen für ONTAP-Versionen, die das Ende des eingeschränkten Supports erreicht haben, mit einer 9‑monatigen Übergangsfrist. Diese Funktion hilft Kunden, rechtzeitig zu handeln und Upgrade-Unterbrechungen zu vermeiden, indem sie während der Übergangsfrist klare Anweisungen gibt.



== 02. Februar 2026



=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== Interaktive Filterung für täglich akkumulierte Burst-Daten

Die Tabelle *Accrued burst by days* im Tab *Consumption trend* unterstützt jetzt interaktives Filtern. Wählen Sie einen beliebigen Balken im Diagramm der aufgelaufenen Ausfälle aus, um nur die Tage innerhalb dieses Abrechnungszeitraums anzuzeigen. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["Tägliche angesammelte Burst-Datennutzung anzeigen"].



==== Erweiterte Datumsbereichsanzeige im Diagramm der kumulierten Ausbrüche

Das Diagramm der aufgelaufenen Spitzenabrechnungen im Tab *Consumption trend* zeigt jetzt für jeden Abrechnungszeitraum vollständige Datumsbereiche an, wie zum Beispiel 01. Okt 2025 bis 31. Okt 2025, anstatt nur Monat und Jahr.



==== Erweiterbare Ansicht der Abonnementdetails

Die Registerkarte *Abonnements* enthält eine Option, um alle Abonnements zu erweitern und gleichzeitig Informationen zu den Performance-Servicelevels für jedes Abonnement anzuzeigen. Weitere Informationen finden Sie unter link:./integrations/subscriptions-tab.html["Details zu Ihren Keystone Abonnements anzeigen"].



==== Neue Spalte Nutzungstyp

Die Registerkarte *Abonnements* enthält eine Spalte *Nutzungstyp*, die anzeigt, ob das Abonnement auf Basis der bereitgestellten, physischen oder logischen Nutzung abgerechnet wird. Weitere Informationen finden Sie unter link:./integrations/subscriptions-tab.html["Details zu Ihren Keystone Abonnements anzeigen"].



== 19. Januar 2026



=== Sicherung und Wiederherstellung



==== ONTAP Volume-Workload-Erweiterungen

Diese Version der ONTAP Volume-Workloads führt die folgenden erweiterten Funktionen ein:

*Unterstützung für mehrere Buckets*: (Private Vorschau) Ab ONTAP 9.17.1 und neueren Versionen können Sie nun die Volumes innerhalb eines Systems mit bis zu 6 Buckets pro System über verschiedene Cloud-Anbieter hinweg schützen.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["Erfahren Sie mehr über die Sicherung von ONTAP Volume-Daten mit NetApp Backup and Recovery."].



==== VMware-Workload-Verbesserungen

Diese Version von VMware-Workloads bietet die folgenden erweiterten Funktionen:

* Die Unterstützung für VMware-Workloads ist jetzt allgemein verfügbar (GA) in NetApp Backup and Recovery.
* Sie können jetzt Gastbetriebssystemdateien und -ordner wiederherstellen.


https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-overview.html["Erfahren Sie mehr über das Wiederherstellen von Gastdateien und -ordnern."]Die



==== Vorschau der Verbesserungen für Hyper-V-Workloads

Diese Version von Hyper-V-Workloads bietet die folgenden erweiterten Funktionen:

* Sie können jetzt Hyper-V-VM-Backups und -Snapshots an einem alternativen Speicherort wiederherstellen. Nutzen Sie diese Funktion, um VM-Versionen auf verschiedenen Hyper-V-Hosts zu verwalten.
* NetApp Backup und Recovery unterstützt jetzt Hyper-V-VMs, die von System Center Virtual Machine Manager (SCVMM) bereitgestellt und auf einer CIFS-Freigabe gehostet werden.
* Sie können nun Schutzgruppen bearbeiten.



NOTE: Nur in dieser Version ist es nicht möglich, die NetApp -Plugins für Hyper-V oder Windows über die Option *Upgrade* im Menü Aktionen zu aktualisieren. Entfernen Sie stattdessen jeden Hyper-V-Host und fügen Sie ihn anschließend wieder hinzu, um die Plugins zu aktualisieren.

https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-restore.html["Erfahren Sie mehr über die Wiederherstellung von Hyper-V-VMs mit NetApp Backup and Recovery."]Die



==== Vorschau der Verbesserungen für KVM-Workloads

Die KVM-Workload-Vorschau schützt jetzt KVM-Hosts und virtuelle Maschinen, die von Apache CloudStack verwaltet werden.

Weitere Informationen zum Schutz von KVM-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Übersicht über den Schutz von KVM-Workloads"] .



=== Ransomware-Resilienz



==== Nicht unterstützte Volumes

Die Berichte zur Ransomware-Resilienz erfassen nun Informationen über unterstützte und nicht unterstützte Volumes im **Zusammenfassungsbericht**. Nutzen Sie diese Informationen, um zu diagnostizieren, warum Volumes in einem System möglicherweise nicht für den Ransomware-Schutz geeignet sind.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Berichte zum Thema Ransomware-Resilienz herunterladen"^].



== 14. Januar 2026



=== Datenklassifizierung



==== Version 1.50

Diese Version der Datenklassifizierung enthält Fehlerbehebungen und die folgenden Aktualisierungen:

.Verbesserungen der benutzerdefinierten Klassifizierung
Die Datenklassifizierung unterstützt jetzt das Erstellen benutzerdefinierter Kategorien für Ihre Daten. Sie können Dateien hochladen, um ein KI-Modell, das die Datenklassifizierung verwendet, um die Kategoriemarkierung auf Daten anzuwenden, feinabzustimmen. Die Benutzeroberfläche für alle benutzerdefinierten Klassifizierungen wurde verbessert.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["Erstellen einer benutzerdefinierten Klassifizierung"^].

.Benutzerdefinierte Definition für veraltete Daten
Die Datenklassifizierung ermöglicht es Ihnen nun, die Definition veralteter Daten so anzupassen, dass sie Ihren organisatorischen Bedürfnissen entspricht. Bisher galten Daten als veraltet, wenn sie zuletzt vor drei Jahren geändert wurden. Veraltete Daten lassen sich nun anhand des Zeitpunkts des letzten Zugriffs _oder_ der letzten Änderung identifizieren; der Zeitraum kann von vor 6 Monaten bis vor 10 Jahren reichen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-stale-data.html["Anpassen der Definition veralteter Daten"^].

.Verbesserte Leistung
Die Ladezeiten für alle Seiten in der Datenklassifizierung, den Datenmapping-Bericht und die Filter auf der Untersuchungsseite wurden verkürzt.

.Geschätzte Bearbeitungszeit für Untersuchungsberichte
Beim Herunterladen eines Untersuchungsberichts zeigt die Datenklassifizierung nun die voraussichtliche Downloadzeit an.



== 12. Januar 2026



=== Konsoleneinrichtung und -verwaltung



==== Konsolenagent 4.3.0

Die Version 4.3.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Konsolenagenten enthält Sicherheitsverbesserungen, Fehlerbehebungen und die folgenden Funktionen:

.Fähigkeit zur Validierung der Netzwerkverbindungen von Konsolenagenten
Sie können nun die Netzwerkverbindungen verbundener Console-Agenten direkt von der NetApp Console aus validieren. Diese Funktion hilft, die Konnektivität zu überprüfen und Probleme mit Console-Agenten zu beheben. Dies ist zusätzlich zur bestehenden Möglichkeit, Netzwerkanalysen über die Befehlszeile (CLI) der Console-Agent-Wartungskonsole auszuführen.

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Erfahren Sie, wie Sie die Konfiguration aus der NetApp Console ausführen."]



==== NetApp Console

Diese Version enthält Folgendes:

.Rollenbasierter Zugriff für Verbundgruppen in der NetApp Console
Die NetApp Console unterstützt die Zuweisung von Rollen zu föderierten Gruppen (z. B. Active Directory-Gruppen) und ermöglicht es Administratoren, das Onboarding und Offboarding von Benutzern auf der Grundlage der Gruppenzugehörigkeit im Identitätsanbieter (IdP) der Organisation zu automatisieren. Diese Funktion reduziert den Verwaltungsaufwand und gewährleistet einen sicheren und konsistenten Zugriff, indem der Konsolenzugriff bei Änderungen der Gruppenzugehörigkeiten sofort aktualisiert wird.

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["Erfahren Sie, wie Sie Ihrer Organisation Zugriff auf eine föderierte Gruppe gewähren."]

.Unterstützung für die Föderation, wenn sich die NetApp Console im eingeschränkten Modus befindet
Sie können jetzt die Föderation für eine NetApp Console -Organisation aktivieren, die sich im eingeschränkten Modus befindet. Dies ermöglicht es Benutzern, sich mit ihren Unternehmensanmeldeinformationen an der Konsole anzumelden und gleichzeitig die Sicherheitsvorteile des eingeschränkten Modus beizubehalten.

.Nur-Lese-Modus
Sie können eine NetApp Console Organisation in den Nur-Lese-Modus versetzen. Im Nur-Lese-Modus können Benutzer Ressourcen und Einstellungen einsehen, aber keine Änderungen vornehmen. Ein Organisationsadministrator oder Superadministrator kann den Nur-Lese-Modus für eine Organisation aktivieren. Wenn der Nur-Lese-Modus aktiviert ist, müssen Benutzer mit administrativen Rechten ihre Berechtigungen manuell erhöhen, um die erforderlichen Änderungen vornehmen zu können.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["Erfahren Sie, wie Sie den Nur-Lese-Modus für eine Konsolenorganisation aktivieren."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html["Erfahren Sie, wie Sie Ihre Rolle aufwerten können, wenn sich Ihre Organisation im Nur-Lese-Modus befindet."]



=== Notfallwiederherstellung



==== Unterstützung für mehrere Konsolenagenten in lokalen Umgebungen

Wenn Sie Disaster Recovery lokal einsetzen, können Sie jetzt für jede vCenter-Instanz einen Console-Agenten bereitstellen und so die Ausfallsicherheit verbessern.

Wenn Sie beispielsweise zwei Standorte haben (Standorte A und B), kann Standort A über den Console Agent A verfügen, der an vCenter 1, ONTAP -Bereitstellung 1 und ONTAP Bereitstellung 2 angebunden ist. Standort B kann über einen Konsolenagenten B verfügen, der an vCenter 2 und ONTAP Bereitstellungen 3 und 4 angebunden ist.

Informationen zum Console-Agenten in der Notfallwiederherstellung finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html#netapp-console-prerequisites["Erstellen des Konsolenagenten"^]Die



==== Fügen Sie nach einem Failover VMs für Replikationspläne hinzu, die datenspeicherbasierten Schutz verwenden.

Wenn ein Failover ausgelöst wird, umfasst jeder Replikationsplan, der datenspeicherbasierten Schutz verwendet, auch VMs, die dem Datenspeicher hinzugefügt wurden, sofern diese erkannt wurden. Sie müssen die Zuordnungsdetails für die hinzugefügten VMs angeben, bevor das Failover abgeschlossen ist.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Ausfallsichere Anwendungen"^].



==== Neue E-Mail-Benachrichtigungen

Die Notfallwiederherstellung bietet nun E-Mail-Benachrichtigungen für die folgenden Ereignisse:

* Annäherung an die Kapazitätsauslastungsgrenze
* Berichtserstellung abgeschlossen
* Jobmisserfolge
* Ablauf der Lizenz oder Verstöße




==== Swagger-Verbesserungen

Sie können nun direkt aus dem Disaster Recovery-Bereich auf die Swagger-Dokumentation zugreifen. Wählen Sie im Disaster Recovery-Menü **Einstellungen** und dann **API-Dokumentation**, um auf Swagger zuzugreifen, oder besuchen Sie diese URL im Inkognito-/Privatmodus Ihres Browsers: link:https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas"^]Die



==== Verbesserte Benutzeroberflächen

Die Notfallwiederherstellung bietet jetzt verbesserte Warnungen und Fehlerbehebungen. Diese Version behebt einen Fehler, der verhinderte, dass abgebrochene Aufträge in der Benutzeroberfläche angezeigt wurden. Stornierte Aufträge sind jetzt sichtbar. Außerdem gibt es eine neue Warnung, wenn dasselbe Zielnetzwerk mehreren verschiedenen Quellnetzwerken zugeordnet wird.



==== Die als Standard hinzugefügte VM-Ordnerstruktur in Replikationsplänen beibehalten

Beim Erstellen einer Replikation ist die neue Standardeinstellung, die Ordnerstruktur der VM beizubehalten. Falls das Wiederherstellungsziel nicht über die ursprüngliche Ordnerhierarchie verfügt, erstellt Disaster Recovery diese. Sie können diese Option deaktivieren, um die ursprüngliche Ordnerhierarchie zu ignorieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Erstellen eines Replikationsplans"^].



=== Ransomware-Resilienz



==== Snapshots in ONTAP replizieren

Ransomware Resilience unterstützt nun das Hinzufügen der Replikation von Snapshots zu einem sekundären ONTAP Standort. Mit Schutzgruppen, die eine Replikationsrichtlinie verwenden, können Sie für jede Arbeitslast an dasselbe Ziel oder an verschiedene Ziele replizieren. Sie können eine Ransomware-Schutzstrategie erstellen, die Replikation beinhaltet, oder die vordefinierte Strategie verwenden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Workloads im Rahmen der Ransomware-Resilienz schützen"^].



==== Workloads von der Ransomware-Resilienz ausschließen

Ransomware Resilience unterstützt jetzt das Ausschließen bestimmter Workloads in einem System vom Schutz und vom Ransomware Resilience Dashboard. Sie können Workloads nach der Erkennung ausschließen und sie wieder einbeziehen, wenn Sie einen Ransomware-Schutz hinzufügen möchten. Für ausgeschlossene Arbeitslasten werden Ihnen keine Kosten in Rechnung gestellt.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html#exclude-workloads["Arbeitslasten ausschließen"^].



==== Benachrichtigungen als in Überprüfung markieren

Ransomware Resilience ermöglicht es Ihnen nun, Warnmeldungen als „In Prüfung“ zu markieren. Verwenden Sie das Label „In Prüfung“, um die Klarheit innerhalb Ihres Teams bei der Priorisierung und dem Management aktiver Ransomware-Bedrohungen zu verbessern.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Warnmeldungen in der Ransomware-Resilienz verwalten"^].



=== Cloud Volumes ONTAP



==== Bevorzugte Abrechnungsoption für Cloud Volumes ONTAP

Sie können nun eine bevorzugte Abrechnungsoption für die Berechnung Ihrer Cloud Volumes ONTAP Nutzung und etwaiger Mehrkosten auswählen. Da das Lizenzmodell Bring Your Own Licenses (BYOL) ab dem 25. Juni 2025 nur noch eingeschränkt verfügbar ist, hat NetApp im Abschnitt *Lizenzierung und Abonnements* der NetApp Console bevorzugte Abrechnungsmethoden hinzugefügt. Sie können entweder Ihr jährliches Marktplatz-Abonnement für die Abrechnung und die Beitreibung von Mehrkosten oder das bestehende BYOL-Modell als bevorzugte Option nutzen. Dies gibt Ihnen die Flexibilität, die Abrechnungsmethode zu wählen, die am besten zur Finanzstrategie und den Nutzungsmustern Ihres Unternehmens passt.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#billing-preferences-and-overages["Abrechnungseinstellungen und Überschreitungen"^]Die



== 10. Dezember 2025



=== Konsoleneinrichtung und -verwaltung



==== Konsolenagent 4.2.0

Die Version 4.2.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Konsolenagenten enthält Sicherheitsverbesserungen, Fehlerbehebungen und die folgenden Funktionen:

.Unterstützung für Google Cloud Infrastructure Manager
NetApp verwendet jetzt Google Cloud Infrastructure Manager (IM) anstelle von Google Cloud Deployment Manager, um Agenten in Google Cloud bereitzustellen und zu verwalten. Diese Änderung wurde vorgenommen, weil Google die Funktion einstellen wird. link:https://docs.cloud.google.com/deployment-manager/docs/deprecations["Cloud-Bereitstellungsmanager"]Die

* Alle neuen Agenten ab Version 4.2.0 verwenden Infrastructure Manager. Sie sollten daher sowohl die Benutzer- als auch die Dienstkontoberechtigungen, die für die Bereitstellung verwendet werden, aktualisieren. link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Das Änderungsprotokoll der Berechtigungen ansehen."^]
* Wenn Sie einen Agenten bereitstellen, erstellt das System auch einen Google Cloud-Bucket zum Speichern der Bereitstellungsdateien.


.Verbesserte Konfigurationsprüfungen für Konsolenagenten
* Der Console-Agent prüft nun bei der Konfigurationsprüfung auch auf veraltete Endpunkte. Wenn Sie die neue Endpunktliste für Version 4.0.0 oder höher noch nicht aktualisiert haben, ist die Installation erfolgreich, wenn das System die vorherige Endpunktliste erreichen kann. link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["Erfahren Sie mehr über die erforderlichen Endpunkte für Console-Agenten."^]
* Führen Sie Konfigurationsprüfungen an installierten Console-Agenten über die Console- oder Agentenwartungskonsole durch, um die Konnektivität zu überprüfen und Probleme zu beheben. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Erfahren Sie, wie Sie Konfigurationsprüfungen auf Console-Agenten durchführen."^]


.Laden Sie die Agentensoftware direkt von der NetApp Console herunter.
Wenn Sie einen Agenten manuell installieren müssen, können Sie die Agentensoftware zusätzlich zur NetApp Support-Website auch direkt über die NetApp Console aufrufen. link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["Erfahren Sie, wie Sie die Console-Agent-Software direkt von der NetApp Console herunterladen können."^]



==== NetApp Console

Diese Version enthält Folgendes:

.Möglichkeit, Benachrichtigungen für ablaufende Anmeldeinformationen einzurichten.
Benachrichtigungen für ablaufende Anmeldeinformationen von Dienstkonten und Verbunddiensten einrichten. Wählen Sie zwischen sieben oder 30 Tagen. Die Konsole zeigt Benachrichtigungen an und versendet E-Mails an Benutzer mit der entsprechenden Rolle. Organisationsadministratoren erhalten Benachrichtigungen über Dienstkonten. Organisationsadministratoren, Föderationsadministratoren und Föderationsbetrachter erhalten Föderationsbenachrichtigungen.

.Lokale Anmeldungen sind nach der Aktivierung der Föderation nicht mehr möglich.
Nach der Aktivierung der Föderation für eine Konsolenorganisation können Benutzer keine lokalen Anmeldungen mehr verwenden und werden zu Föderationsanmeldungen weitergeleitet.

.Verbesserungen der Benutzerfreundlichkeit der Speicherverwaltungsseiten
Detaillierte Informationen zu Ihren ONTAP On-Premises-Systemen (und FSx für ONTAP) können jetzt einfacher über die Speicherverwaltungsseiten angezeigt und verwaltet werden.

* Die Seite * Discoverable systems* trennt die zusammenfassenden Informationen von der Registerkartenansicht der verfügbaren Systeme und erleichtert so die Anzeige umfassender Informationen über auffindbare Systeme.




=== On-Premises- ONTAP -Cluster



==== Verbesserungen der Benutzerfreundlichkeit bei der Anzeige von ONTAP -Systemen über die NetApp Console (nur Standardmodus)

Die Seite *Systeme* in der NetApp Console wurde hinsichtlich Übersichtlichkeit und Benutzerfreundlichkeit bei der Verwaltung von Volumes und Clustern verbessert. Diese Aktualisierungen gleichen die Benutzererfahrung stärker an den System Manager für neuere ONTAP Versionen an und vereinfachen die Navigation.

.Clusterkapazität ist für ONTAP Versionen 9.5 und höher enthalten (nur Konsolen-Standardmodus).
Auf der Seite *Systeme > Übersicht* wird die Clustergröße zusammen mit der ONTAP Version für Cluster angezeigt, auf denen ONTAP 9.5 und höher ausgeführt wird.

Für NetApp Console im eingeschränkten Modus oder ONTAP Versionen 9.5 und niedriger bleiben die Informationen zum bereitgestellten Volume unverändert.

.Die Registerkarte „Volumes“ auf der Seite „Systeme“ zeigt standardmäßig die Rasteransicht an, wenn Sie mehr als 20 lokale ONTAP Cluster haben.
Wenn Sie mehr als 20 lokale ONTAP Cluster in der NetApp Console verwalten, wird die Registerkarte *Volume* standardmäßig in der Rasteransicht angezeigt, um die Navigation zu vereinfachen. Die Kartenansicht ist deaktiviert.

Diese Änderung gilt nur für den Standardmodus und für ONTAP Versionen ab 9.6.



== 9. Dezember 2025



=== Notfallwiederherstellung



==== Beibehaltung der Ordnerhierarchie

Standardmäßig behält Disaster Recovery die VM-Inventarhierarchie (Ordnerstruktur) beim Failover bei. Falls das Wiederherstellungsziel den erforderlichen Ordner nicht enthält, wird dieser von Disaster Recovery erstellt.

Sie können diese Einstellung nun überschreiben, indem Sie einen neuen übergeordneten VM-Ordner festlegen oder die Option **Ursprüngliche Ordnerhierarchie beibehalten** deaktivieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Erstellen eines Replikationsplans"].



==== Optimierte Aktualisierung des Konsolenagenten

Die Disaster-Recovery-Lösung unterstützt nun einen optimierten Prozess für die Verwendung mehrerer Console-Agenten in einer Arbeitsumgebung. Um zwischen verschiedenen Console-Agenten zu wechseln, müssen Sie Ihre vCenter-Konfiguration bearbeiten, die Anmeldeinformationen neu ermitteln und die Replikationspläne aktualisieren, um den neuen Console-Agenten zu verwenden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agent.html["Switch Console-Agenten"].



== 8. Dezember 2025



=== Sicherung und Wiederherstellung



==== VMware Workloads Vorschau-Verbesserungen

Die Vorschauversion von VMware-Workloads führt die folgenden erweiterten Funktionen ein:

* Sie können Backups und Snapshots jetzt an einem alternativen Speicherort wiederherstellen. Dies ist nützlich, wenn Sie Versionen einer VM auf verschiedenen VMware vCenter-Bereitstellungen, VMware ESXi-Hosts oder VMware-Datenspeichern verwalten möchten.


link:br-use-vmware-restore.html["Erfahren Sie mehr über die Wiederherstellung von VMware-VMs mit NetApp Backup and Recovery."].

* Sie können nun bestimmte virtuelle VMware-Festplatten (VMDK-Images) entweder von einem primären oder einem sekundären Speicherort wiederherstellen, was eine feinere Kontrolle über die Wiederherstellung von VM-Daten ermöglicht.


link:br-use-vmware-restore-vmdks-from-backups.html["Erfahren Sie mehr über die Wiederherstellung virtueller VMware-Festplatten mit NetApp Backup and Recovery."].



=== Datenklassifizierung



==== Version 1.49

Diese Version der Datenklassifizierung enthält Fehlerbehebungen und die folgenden Aktualisierungen:

.Überwachen Sie Kennzahlen und Leistung im Dashboard für die Gesundheitsüberwachung.
Die Datenklassifizierung bietet jetzt ein Dashboard zur Gesundheitsüberwachung, das eine Echtzeitüberwachung Ihrer Ressourcen sowie Einblicke in Speichernutzung, Festplattennutzung, Festplattenauslastung und mehr ermöglicht. Mithilfe der Erkenntnisse aus dem Dashboard zur Gesundheitsüberwachung können Sie die Infrastruktur Ihrer Bereitstellung überprüfen und Einblicke gewinnen, um Speicher und Leistung zu optimieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Überwachen Sie den Zustand der Datenklassifizierung"].

.Verbesserte Ladeleistung
Die Ladeleistung aller Seiten in der Datenklassifizierung wurde verbessert, um ein effizienteres Benutzererlebnis zu schaffen.



=== Ransomware-Resilienz



==== Die Blockierung von Erweiterungen ist auf Workload-Ebene aktiviert.

Wenn Sie die Erweiterungsblockierung aktivieren, erfolgt die Aktivierung nun auf Workload-Ebene und nicht mehr auf Ebene der Speicher-VM.



==== Benutzerverhaltenswarnungsstatus bearbeiten

Ransomware Resilience ermöglicht es Ihnen nun, den Status von Warnmeldungen zum Benutzerverhalten zu bearbeiten. Sie können Warnmeldungen manuell verwerfen und beheben.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Warnmeldungen in der Ransomware-Resilienz verwalten"^].



==== Unterstützung für mehrere Konsolenagenten

Ransomware Resilience unterstützt jetzt die Verwendung mehrerer Console-Agenten zur Verwaltung derselben Systeme.

Weitere Informationen zu Console-Agenten finden Sie unterlink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Erstellen eines Konsolenagenten"] Die



=== Cloud Volumes ONTAP



==== Möglichkeit zur Leistungssteigerung von Premium SSD v2-Festplatten in Azure

Sie können die Leistung von Premium SSD v2 Managed Disks in Azure jetzt verbessern, indem Sie die IOPS- und Durchsatzparameter ändern. Mithilfe dieser Funktion können Sie die Speicherleistung Ihrer Systeme auf Basis Ihrer Arbeitslastanforderungen optimieren.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Verwalten der Premium-SSD-v2-Festplattenleistung für Cloud Volumes ONTAP in Azure"^].



==== Vereinfachte Gebührenberechnung für Essentials-Lizenzen bei Überschreitung des Lizenzumfangs

Bei den jährlichen Verträgen/privaten Angeboten des Cloud Volumes ONTAP Marktplatzes sind die Berechnungen für die Überschreitung von Essentials-Lizenzen nun an die Bring Your Own License (BYOL)-Pakete angeglichen. Bisher wurden Mehrverbrauchsmengen zu den stundenweisen Marktpreisen für das jeweilige Essentials-Paket abgerechnet. Wenn Ihr jährlicher Marketplace-Vertrag mehrere Essentials-Pakete umfasst, berechnet die NetApp Console die Mehrkosten für ein Essentials-Paket auf Basis der verfügbaren Kapazität eines höherpreisigen Essentials-Pakets in Ihrem Abonnement. Dies vereinfacht die Berechnung von Mehrkosten für Essentials-Pakete und gewährleistet einen reibungslosen Übergang von der BYOL-Lizenzierung zu einem abonnementbasierten Modell.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Wie Überschreitungen bei Essentials-Lizenzen abgerechnet werden"^]



==== Unterstützung für Azure Edsv6-Größenserien

Ab Cloud Volumes ONTAP 9.17.1 können Sie VMs der Azure Edsv6-Serie über die NetApp Console für neue Cloud Volumes ONTAP Instanzen bereitstellen. Cloud Volumes ONTAP 9.17.1 und spätere Versionen unterstützen bei neuen Bereitstellungen nur noch VMs der Generation 2. Diese Geräte der zweiten Generation sind mit den neuesten Technologien kompatibel, wie z. B. Unified Extensible Firmware Interface (UEFI), Azure Boost-Systemen und NVMe. Sie eignen sich ideal für speicherintensive Systeme und Anwendungen, die einen schnellen, lokalen Speicher benötigen, wie z. B. Datenbankserver und Analyse-Engines.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Unterstützte Konfigurationen für Cloud Volumes ONTAP in Azure"^]



=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== Umbenannt in „Aufgelaufene Auslösekapazität“

Die Bezeichnung *Accrued burst capacity* wird in *Accrued burst* umbenannt.



== 01. Dezember 2025



=== Notfallwiederherstellung



==== Unterstützung für Google Cloud VMware Engine mit Google Cloud NetApp Volumes

NetApp Disaster Recovery unterstützt jetzt Google Cloud VMware Engine unter Verwendung von Google Cloud NetApp Volumes für Migrations-, Failover-, Failback- und Testvorgänge. Diese Integration ermöglicht nahtlose Disaster-Recovery-Workflows zwischen lokalen Umgebungen und Google Cloud.

Bitte überprüfen Sie dielink:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html["Voraussetzungen"] Undlink:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["Einschränkungen"] für Google Cloud.



== 27. November 2025



=== Google Cloud NetApp Volumes



==== Änderungen der Anmeldeinformationen für die Google Cloud Platform

Da Kunden immer mehr Google Cloud NetApp Volumes Systeme einrichten und autorisieren, hat sich die Verwaltung der Zugangsdaten verändert.

Die Anmeldeinformationen für NetApp Volumes-Systeme werden jetzt in einem Google Cloud-Backend gespeichert, beispielsweise im Cloud Key Management-Dienst oder einem ähnlichen Dienst. Beim Erstellen eines neuen Systems werden die Anmeldeinformationen für die Identitätswechselfunktion des Dienstkontos verwendet.



== 24. November 2025



=== Keystone

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



==== Tracking-ID für Abonnements mit Abdeckungslücke

Im Benachrichtigungsfeld *Vervollständigen Sie Ihre Abdeckung* unter *Überwachung > Alarmmonitore* wird nun für jedes Abonnement neben der Abonnementnummer die Tracking-ID angezeigt.



== 17. November 2025



=== Amazon FSX für ONTAP



==== System Manager verfügbar bei Verwendung eines AWS Lambda-Links

Die ONTAP System Manager-Schnittstelle kann mit einer AWS Lambda-Verbindung verwendet werden, um erweiterte ONTAP Operationen durchzuführen. Dies bietet eine Alternative zur Verwendung eines Konsolenagenten mit System Manager für die direkte Verwaltung eines FSx for ONTAP -Dateisystems über die Konsole. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Erfahren Sie mehr über die Verwendung von Links für fortgeschrittene ONTAP Operationen."^]
