= Hyper-V-Workload-Verbesserungen
:allow-uri-read: 




=== Hyper-V-Workload-Verbesserungen

In dieser Version werden fﾃｼr Hyper-V-Workloads die folgenden Verbesserungen eingefﾃｼhrt:

* *VMs auf SAN-Speicher schﾃｼtzen*: Sie kﾃｶnnen jetzt VMs auf SAN-Objektspeicher schﾃｼtzen.
* *Verbesserungen bei der Wiederherstellung an alternativen Speicherorten*: Sie kﾃｶnnen jetzt von primﾃ､ren und sekundﾃ､ren Speicherorten fﾃｼr VMs auf SAN-Speicher an einem alternativen Speicherort wiederherstellen.
* *Dateien und Ordner in einer Gast-VM*: Sie kﾃｶnnen jetzt Dateien und Ordner aus einem Snapshot auf dem primﾃ､ren Speicher in einer Gast-Windows-VM wiederherstellen. Diese Funktion wird nur fﾃｼr CIFS-VMs unterstﾃｼtzt.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["ﾃ彙ersicht zum Schutz von Hyper-V-Workloads"].



=== Verbesserungen fﾃｼr KVM-Workloads

In dieser Version wird fﾃｼr KVM-Workloads die folgende Verbesserung eingefﾃｼhrt:

*Wiederherstellung an alternativem Speicherort*: Sie kﾃｶnnen KVM-VMs jetzt an einem alternativen Zielort wiederherstellen (diese Funktion ist jetzt allgemein verfﾃｼgbar).

Weitere Informationen zum Schutz von KVM-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["ﾃ彙ersicht ﾃｼber den Schutz von KVM-Workloads"] .



=== Verbesserungen der Oracle Database Workloads

In dieser Version werden die folgenden Verbesserungen fﾃｼr Oracle Database workloads eingefﾃｼhrt:

* *Unterstﾃｼtzung fﾃｼr Oracle AI Database 26ai*: Backup und Recovery unterstﾃｼtzen jetzt Oracle AI Database 26ai.
* *Unterstﾃｼtzung fﾃｼr die Backup-Verifizierung*: Sie kﾃｶnnen jetzt Backup-Richtlinien konfigurieren, um die Integritﾃ､t Ihrer Oracle Datenbank-Backups automatisch zu ﾃｼberprﾃｼfen.


Weitere Informationen zum Schutz von Oracle Database-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["ﾃ彙ersicht zum Schutz von Oracle Database-Workloads"].



=== VMware-Workload-Verbesserungen

In dieser Version fﾃｼhrt VMware workloads die folgenden Verbesserungen ein:

* *Unterstﾃｼtzung fﾃｼr datenspeicherﾃｼbergreifende Schutzgruppen*: Sie kﾃｶnnen nun das Verhalten von Schutzgruppen beim Schutz virtueller Maschinen auswﾃ､hlen, deren virtuelle Festplatten sich ﾃｼber mehrere Datenspeicher erstrecken.
* *Klonunterstﾃｼtzung*: Sie kﾃｶnnen jetzt Klone von Snapshots virtueller Maschinen aus dem primﾃ､ren und sekundﾃ､ren Speicher erstellen.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["ﾃ彙erblick ﾃｼber den Schutz von VMware-Workloads"].
