= Console Agent 4.6.0
:allow-uri-read: 




=== Console Agent 4.6.0

Die Version 4.6.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Console-Agenten enthält Sicherheitsverbesserungen und Fehlerbehebungen sowie die folgende neue Funktion.

.Unterstützung für Konfigurationsprüfungen des benötigten Speicherplatzes
Sie können mithilfe von Konfigurationsprüfungen sicherstellen, dass der für den Konsolenagenten erforderliche Speicherplatz verfügbar ist. Sie können Konfigurationsprüfungen von der Konsole oder der Wartungskonsole des Agenten aus durchführen. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html["Erfahren Sie mehr über die Durchführung von Konfigurationsprüfungen auf dem Konsolenagenten"^]

.Aktualisieren Sie einen mit vCenter bereitgestellten Console-Agenten mithilfe einer ISO
Wenn Sie einen Console-Agenten in vCenter mithilfe einer OVA bereitgestellt haben, können Sie ihn jetzt auf eine neue Version aktualisieren, indem Sie eine ISO an die VM anhängen und das Upgrade über die VM-Wartungskonsole ausführen. link:https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-agent.html["Erfahren Sie, wie Sie einen von vCenter bereitgestellten Konsolenagenten aktualisieren"^]
