= Konsolenagent 4.3.0
:allow-uri-read: 




=== Konsolenagent 4.3.0

Die Version 4.3.0 unterstützt sowohl den Standardmodus als auch den eingeschränkten Modus.

Diese Version des Konsolenagenten enthält Sicherheitsverbesserungen, Fehlerbehebungen und die folgenden Funktionen:

.Fähigkeit zur Validierung der Netzwerkverbindungen von Konsolenagenten
Sie können jetzt die Netzwerkverbindungen verbundener Console-Agenten direkt über die NetApp Console überprüfen. Diese Funktion hilft bei der Überprüfung der Konnektivität und der Fehlerbehebung bei Problemen mit Console-Agenten.

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Erfahren Sie, wie Sie Konfigurationsprüfungen auf Console-Agenten durchführen."]



=== NetApp Console

Diese Version enthält Folgendes:

.Unterstützung für die Föderation, wenn sich die NetApp Console im eingeschränkten Modus befindet
Sie können jetzt die Föderation für eine NetApp Console -Organisation aktivieren, die sich im eingeschränkten Modus befindet. Dies ermöglicht es Benutzern, sich mit ihren Unternehmensanmeldeinformationen an der Konsole anzumelden und gleichzeitig die Sicherheitsvorteile des eingeschränkten Modus beizubehalten.

.Nur-Lese-Modus
Sie können eine NetApp Console Organisation in den Nur-Lese-Modus versetzen. Im Nur-Lese-Modus können Benutzer Ressourcen und Einstellungen einsehen, aber keine Änderungen vornehmen. Ein Organisationsadministrator oder Superadministrator kann den Nur-Lese-Modus für eine Organisation aktivieren. Wenn der Nur-Lese-Modus aktiviert ist, müssen Benutzer mit administrativen Rechten ihre Berechtigungen manuell erhöhen, um die erforderlichen Änderungen vornehmen zu können.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["Erfahren Sie, wie Sie den Nur-Lese-Modus für eine Konsolenorganisation aktivieren."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings["Erfahren Sie, wie Sie Ihre Rolle aufwerten können, wenn sich Ihre Organisation im Nur-Lese-Modus befindet."]
