= Veröffentlichung im privaten Modus (4.4.0)
:allow-uri-read: 




=== Veröffentlichung im privaten Modus (4.4.0)

Eine neue Version des privaten Modus steht jetzt zum Download aus dem https://mysupport.netapp.com/site/downloads["NetApp Support Site"^] bereit.



==== BlueXP Private-Modus ist jetzt NetApp Console Private-Modus

NetApp Console 4.4.0 ist die erste Version von NetApp Console im privaten Modus.

Die NetApp Console, die auf der verbesserten und restrukturierten BlueXP-Grundlage basiert, ermöglicht die zentrale Verwaltung von NetApp Speicher und NetApp Data Services in On-Premises- und Cloud-Umgebungen auf Unternehmensebene – und liefert Echtzeit-Einblicke, schnellere Arbeitsabläufe und eine vereinfachte Administration, die hochsicher und konform ist.

Erfahren Sie mehr über die neue NetApp Console in der https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2025-10-06.html["Was ist neu auf der NetApp Console-Seite"^].

Die Version 4.4.0 enthält Aktualisierungen der folgenden NetApp Console-Komponenten und -Dienste.

[cols="3*"]
|===
| Komponente oder Service | In dieser Version enthalten | Änderungen seit der vorherigen privaten Modus-Version 


| Konsolenagent | 4.4.0 | Gehen Sie zu  https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2026-02-09.html["Was ist neu auf der NetApp Console-Seite"^] und informieren Sie sich über die Änderungen in Version 4.4.0. 


| Datensicherung und Wiederherstellung | 5.0.3 (2. März 2026) | Gehe zu https://docs.netapp.com/us-en/data-services-backup-recovery/whats-new.html["Was ist neu auf der Seite NetApp Backup and Recovery"^]. 


| Einstufung | 1.5.1 (9. Februar 2026) | Gehe zu https://docs.netapp.com/us-en/data-services-data-classification/whats-new.html["Was ist neu auf der Seite NetApp Klassifizierung"^]. 
|===