= 3-2-1-Sicherungsrichtlinienerstellung während der Sicherungsaktivierung
:allow-uri-read: 




=== 3-2-1-Sicherungsrichtlinienerstellung während der Sicherungsaktivierung

Bisher mussten benutzerdefinierte Richtlinien erstellt werden, bevor Sie einen Snapshot, eine Replikation oder ein Backup initiierten.  Jetzt können Sie während des Sicherungsaktivierungsprozesses mithilfe der BlueXP backup and recovery eine Richtlinie erstellen.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Weitere Informationen zu Richtlinien"] .



=== Unterstützung für die schnelle Wiederherstellung von ONTAP -Volumes auf Abruf

BlueXP backup and recovery bietet jetzt die Möglichkeit, eine „schnelle Wiederherstellung“ eines Volumes aus dem Cloud-Speicher auf ein Cloud Volumes ONTAP System durchzuführen.  Die schnelle Wiederherstellung ist ideal für Notfallwiederherstellungssituationen, in denen Sie so schnell wie möglich Zugriff auf ein Volume bereitstellen müssen.  Bei einer schnellen Wiederherstellung werden die Metadaten aus der Sicherungsdatei auf einem Volume wiederhergestellt, anstatt die gesamte Sicherungsdatei wiederherzustellen.

Auf dem Cloud Volumes ONTAP -Zielsystem muss ONTAP Version 9.13.0 oder höher ausgeführt werden. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Erfahren Sie mehr über die Wiederherstellung von Daten"] .

Der BlueXP backup and recovery zeigt auch Informationen zum Fortschritt von Schnellwiederherstellungsjobs an.
