= Flash-Cache und Unterstützung für hohe Schreibgeschwindigkeit in Google Cloud
:allow-uri-read: 


Die folgenden Änderungen wurden mit der Version 3.9.32 des Connectors eingeführt.



=== Flash-Cache und Unterstützung für hohe Schreibgeschwindigkeit in Google Cloud

Flash-Cache und hohe Schreibgeschwindigkeit können in Google Cloud für Cloud Volumes ONTAP 9.13.1 und höher separat aktiviert werden.  Eine hohe Schreibgeschwindigkeit ist auf allen unterstützten Instanztypen verfügbar.  Flash Cache wird auf den folgenden Instanztypen unterstützt:

* n2-Standard-16
* n2-Standard-32
* n2-Standard-48
* n2-Standard-64


Sie können diese Funktionen einzeln oder zusammen sowohl bei Einzelknoten- als auch bei Hochverfügbarkeitspaarbereitstellungen verwenden.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html["Starten Sie Cloud Volumes ONTAP in Google Cloud"^]



=== Verbesserungen bei Nutzungsberichten

Es stehen nun verschiedene Verbesserungen der angezeigten Informationen in den Nutzungsberichten zur Verfügung.  Im Folgenden sind die Verbesserungen der Nutzungsberichte aufgeführt:

* Die Einheit TiB ist jetzt im Namen der Spalten enthalten.
* Ein neues Feld „Knoten“ für Seriennummern ist jetzt enthalten.
* Im Nutzungsbericht der Storage-VMs ist jetzt eine neue Spalte „Workload-Typ“ enthalten.
* Die Namen der Arbeitsumgebungen sind jetzt in den Berichten zur Speicher-VM- und Volume-Nutzung enthalten.
* Der Datenträgertyp „Datei“ trägt jetzt die Bezeichnung „Primär (Lesen/Schreiben)“.
* Der Datenträgertyp „sekundär“ trägt jetzt die Bezeichnung „Sekundär (DP)“.


Weitere Informationen zu Nutzungsberichten finden Sie unterlink:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#download-usage-reports["Nutzungsberichte herunterladen"^] .
