= Kleine und mittlere Bereitstellungen vorübergehend nicht verfügbar
:allow-uri-read: 




=== Kleine und mittlere Bereitstellungen vorübergehend nicht verfügbar

Wenn Sie eine Instanz der BlueXP classification in AWS bereitstellen, ist die Option zum Auswählen von *Bereitstellen > Konfiguration* und zum Auswählen einer kleinen oder mittelgroßen Instanz derzeit nicht verfügbar.  Sie können die Instanz weiterhin mit der großen Instanzgröße bereitstellen, indem Sie *Bereitstellen > Bereitstellen* auswählen.



=== Wenden Sie Tags auf bis zu 100.000 Elemente von der Seite „Untersuchungsergebnisse“ an

In der Vergangenheit konnten Sie auf der Seite „Untersuchungsergebnisse“ Tags immer nur auf eine Seite gleichzeitig anwenden (20 Elemente).  Jetzt können Sie *alle* Elemente auf den Seiten mit den Untersuchungsergebnissen auswählen und allen Elementen Tags zuweisen – bis zu 100.000 Elementen gleichzeitig. https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assigning-tags-to-files["So geht's"] .



=== Identifizieren Sie doppelte Dateien mit einer Mindestdateigröße von 1 MB

Die BlueXP classification diente früher nur zur Identifizierung doppelter Dateien, wenn die Dateien 50 MB oder größer waren.  Jetzt können doppelte Dateien ab 1 MB identifiziert werden.  Sie können die Filter „Dateigröße“ und „Duplikate“ auf der Untersuchungsseite verwenden, um zu sehen, welche Dateien einer bestimmten Größe in Ihrer Umgebung dupliziert sind.
