= Es wurde Unterstützung für die Sicherung von Volumes in Buckets auf S3-konfigurierten ONTAP Systemen hinzugefügt.
:allow-uri-read: 


[IMPORTANT]
====
* Aufgrund einer wichtigen Sicherheitsverbesserung benötigt Ihr Connector jetzt ausgehenden Internetzugriff auf einen zusätzlichen Endpunkt, um Sicherungs- und Wiederherstellungsressourcen innerhalb Ihrer öffentlichen Cloud-Umgebung zu verwalten.  Wenn dieser Endpunkt nicht zur Liste der zulässigen Endpunkte in Ihrer Firewall hinzugefügt wurde, wird in der Benutzeroberfläche die Fehlermeldung „Dienst nicht verfügbar“ oder „Dienststatus konnte nicht ermittelt werden“ angezeigt:
+
\https://netapp-cloud-account.auth0.com

* Wenn Sie das Paket „CVO Professional“ verwenden, mit dem Sie Cloud Volumes ONTAP und BlueXP backup and recovery bündeln können, ist jetzt ein PAYGO-Abonnement für Backup und Recovery erforderlich.  Dies war in der Vergangenheit nicht erforderlich.  Für das Abonnement für Backup und Wiederherstellung für berechtigte Cloud Volumes ONTAP Systeme fallen keine Gebühren an, es ist jedoch erforderlich, wenn Sie Backups auf neuen Volumes konfigurieren.


====


=== Es wurde Unterstützung für die Sicherung von Volumes in Buckets auf S3-konfigurierten ONTAP Systemen hinzugefügt.

Jetzt können Sie ein ONTAP System verwenden, das für den Simple Storage Service (S3) konfiguriert wurde, um Volumes im Objektspeicher zu sichern.  Dies wird sowohl für lokale ONTAP -Systeme als auch für Cloud Volumes ONTAP Systeme unterstützt.  Diese Konfiguration wird in Cloud-Bereitstellungen und an lokalen Standorten ohne Internetzugang (eine Bereitstellung im „privaten“ Modus) unterstützt.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["Mehr erfahren"] .



=== Jetzt können Sie vorhandene Snapshots von einem geschützten Volume in Ihre Sicherungsdateien einschließen

In der Vergangenheit hatten Sie die Möglichkeit, vorhandene Snapshot-Kopien von Lese-/Schreib-Volumes in Ihre erste Sicherungsdatei im Objektspeicher aufzunehmen (anstatt mit der aktuellsten Snapshot-Kopie zu beginnen).  Vorhandene Snapshot-Kopien von schreibgeschützten Volumes (Datenschutzvolumes) wurden nicht in die Sicherungsdatei aufgenommen.  Jetzt können Sie wählen, ob ältere Snapshot-Kopien in die Sicherungsdatei für „DP“-Volumes aufgenommen werden sollen.

Der Sicherungsassistent zeigt am Ende der Sicherungsschritte eine Eingabeaufforderung an, in der Sie diese „vorhandenen Snapshots“ auswählen können.



=== BlueXP backup and recovery unterstützt keine automatische Sicherung von zukünftig hinzugefügten Volumes mehr

Bisher konnten Sie im Sicherungsassistenten ein Kontrollkästchen aktivieren, um die ausgewählte Sicherungsrichtlinie auf alle zukünftigen Volumes anzuwenden, die dem Cluster hinzugefügt werden.  Diese Funktion wurde aufgrund von Benutzerfeedback und mangelnder Nutzung dieser Funktion entfernt.  Sie müssen Sicherungen für alle neuen Volumes, die dem Cluster hinzugefügt werden, manuell aktivieren.



=== Die Seite zur Jobüberwachung wurde mit neuen Funktionen aktualisiert

Die Seite „Jobüberwachung“ bietet jetzt mehr Informationen zur 3-2-1-Sicherungsstrategie.  Der Dienst bietet außerdem zusätzliche Warnmeldungen im Zusammenhang mit der Sicherungsstrategie.

Der Typfilter „Sicherungslebenszyklus“ wurde in „Aufbewahrung“ umbenannt.  Verwenden Sie diesen Filter, um den Lebenszyklus der Sicherung zu verfolgen und das Ablaufdatum aller Sicherungskopien zu ermitteln.  Der Auftragstyp „Aufbewahrung“ erfasst alle Snapshot-Löschaufträge, die auf einem Volume initiiert wurden, das durch BlueXP backup and recovery geschützt ist.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Erfahren Sie mehr über den aktualisierten Job Monitor"] .
