= Verbesserungen bei BlueXP backup and recovery für Anwendungen (Cloud-nativ)
:allow-uri-read: 




=== Verbesserungen bei BlueXP backup and recovery für Anwendungen (Cloud-nativ)

* Microsoft SQL Server-Datenbank
+
** Unterstützt die Sicherung, Wiederherstellung und Wiederherstellung von Microsoft SQL Server-Datenbanken auf Amazon FSx for NetApp ONTAP
** Alle Vorgänge werden nur über REST-APIs unterstützt.


* SAP HANA-Systeme
+
** Während der Systemaktualisierung werden die automatischen Ein- und Aushänge der Volumes mithilfe von Workflows statt Skripts durchgeführt.
** Unterstützt das Hinzufügen, Entfernen, Bearbeiten, Löschen, Warten und Aktualisieren des Plug-In-Hosts über die Benutzeroberfläche






=== Verbesserungen bei BlueXP backup and recovery für Anwendungen (Hybrid)

* Unterstützt Datensperre und Ransomware-Schutz
* Unterstützt das Verschieben von Backups von StorageGrid in die Archivebene
* Unterstützt die Sicherung von MongoDB-, MySQL- und PostgreSQL-Anwendungsdaten von lokalen ONTAP Systemen auf Amazon Web Services, Microsoft Azure, Google Cloud Platform und StorageGRID.  Sie können die Daten bei Bedarf wiederherstellen.




=== Verbesserungen bei BlueXP backup and recovery für virtuelle Maschinen

* Unterstützung für das Connector-Proxy-Bereitstellungsmodell

